const soldierData = [
    { rank: 'CAPT', name: 'JOGINDER SINGH GHARAYA', regiment: 'BIHAR' },
    { rank: 'HAV', name: 'AMAR SINGH', regiment: 'PUNJAB' },
    { rank: 'NK', name: 'HARDIAL SINGH (P)', regiment: 'SIKH' },
    { rank: 'SEP', name: 'SEWA SINGH', regiment: 'SIKH' },
    { rank: 'SEP', name: 'DARYAO', regiment: 'GRENADIERS' },
    { rank: 'MAJ', name: 'GURCHARAN SINGH', regiment: 'ARTILLERY' },
    { rank: 'SOWAR', name: 'PRITHI SINGH', regiment: 'ARMOURED' },
    { rank: 'LIEUT', name: 'RAJINDER SINGH', regiment: 'JAT' },
    { rank: 'NAIK', name: 'SANT RAM', regiment: 'RAJPUT' },
    { rank: 'CAPT', name: 'SUDHIR KUMAR', regiment: 'MARATHA' },
    { rank: 'SEP', name: 'RAJESH KUMAR', regiment: 'GORKHA' },
    { rank: 'HAV', name: 'RAVINDER SINGH', regiment: 'BENGAL ENGINEERS' },
    { rank: 'SOWAR', name: 'BALVINDER SINGH', regiment: 'CAVALRY' },
    { rank: 'MAJ', name: 'ASHOK KUMAR', regiment: 'ARMY AIR DEFENSE' },
    { rank: 'LIEUT', name: 'MUKESH SINGH', regiment: 'MAHAR REGIMENT' },
    { rank: 'CAPT', name: 'PRAVEEN KUMAR', regiment: 'ASSAM RIFLES' },
    { rank: 'SEP', name: 'RAMESH KUMAR', regiment: 'SIKH LI' },
    { rank: 'NK', name: 'HARPREET SINGH', regiment: 'PUNJAB' },
    { rank: 'LIEUT', name: 'VIVEK KUMAR', regiment: 'RIFLE REGIMENT' },
    { rank: 'HAV', name: 'SURESH KUMAR', regiment: 'MYSORE' },
    { rank: 'SOWAR', name: 'RAM SINGH', regiment: 'JAT REGIMENT' },
    { rank: 'NAIK', name: 'PRADEEP KUMAR', regiment: 'RAJPUTANA' },
    { rank: 'CAPT', name: 'ANIL KUMAR', regiment: 'JAT' },
    { rank: 'HAV', name: 'RAMESH KUMAR', regiment: 'BENGAL' },
    { rank: 'MAJ', name: 'VIKAS SINGH', regiment: 'PUNJAB' },
    { rank: 'SOWAR', name: 'KARAN SINGH', regiment: 'CAVALRY' },
    { rank: 'LIEUT', name: 'KAMALJEET SINGH', regiment: 'RAJPUT' },
    { rank: 'CAPT', name: 'SANJAY KUMAR', regiment: 'MAHAR' },
    { rank: 'NK', name: 'MANJEET SINGH', regiment: 'JAT' },
    { rank: 'HAV', name: 'JAGDISH KUMAR', regiment: 'SITRA' },
    { rank: 'SOWAR', name: 'SHAMSHER SINGH', regiment: 'RAJPUTANA' },
    { rank: 'SEP', name: 'RAVI KUMAR', regiment: 'SOUTHERN COMMAND' },
    { rank: 'LIEUT', name: 'SUDHIR SINGH', regiment: 'RIFLE' },
    { rank: 'MAJ', name: 'RATAN SINGH', regiment: 'PUNJAB' },
    { rank: 'NAIK', name: 'AMIT KUMAR', regiment: 'MEERUT' },
    { rank: 'SEP', name: 'RAJINDER SINGH', regiment: 'JAMMU & KASHMIR' },
    { rank: 'CAPT', name: 'BIR SINGH', regiment: 'MYSORE' },
    { rank: 'SOWAR', name: 'SANTOSH KUMAR', regiment: 'SIKH' },
    { rank: 'LIEUT', name: 'HARDIP SINGH', regiment: 'RAJPUTANA' },
    { rank: 'HAV', name: 'ANAND KUMAR', regiment: 'ASSAM' },
    { rank: 'SEP', name: 'PREM SINGH', regiment: 'JAT' },
    { rank: 'SOWAR', name: 'PRAVEEN KUMAR', regiment: 'RIFLE' },
    { rank: 'MAJ', name: 'SUBHASH SINGH', regiment: 'CAVALRY' },
    { rank: 'LIEUT', name: 'NAVEEN SINGH', regiment: 'ARMY' },
    { rank: 'SEP', name: 'ASHOK KUMAR', regiment: 'MEERUT' },
    { rank: 'NAIK', name: 'RAVI KUMAR', regiment: 'SITRA' },
    { rank: 'CAPT', name: 'SURESH KUMAR', regiment: 'SIKH' },
    { rank: 'HAV', name: 'MANOHAR SINGH', regiment: 'PUNJAB' },
    { rank: 'SOWAR', name: 'SATISH KUMAR', regiment: 'SOUTHERN COMMAND' },
    { rank: 'SEP', name: 'SANDEEP KUMAR', regiment: 'GORKHA' },
    { rank: 'MAJ', name: 'RAJESH SINGH', regiment: 'ARMY' },
    { rank: 'CAPT', name: 'RAVI PRAKASH', regiment: 'ARMY' },
    { rank: 'NAIK', name: 'RAVI KUMAR', regiment: 'JAT' },
    { rank: 'LIEUT', name: 'VIKAS KUMAR', regiment: 'RAJPUT' },
    { rank: 'HAV', name: 'PRADEEP SINGH', regiment: 'JAT' },
    { rank: 'SOWAR', name: 'JATINDER SINGH', regiment: 'CAVALRY' },
    { rank: 'CAPT', name: 'RAJINDER KUMAR', regiment: 'PUNJAB' },
    { rank: 'SEP', name: 'GURMEET SINGH', regiment: 'JAT' },
    { rank: 'SEP', name: 'KARAMJEET SINGH', regiment: 'JAT' },
{ rank: 'NAIK', name: 'RAJINDER KUMAR', regiment: 'GORKHA' },
{ rank: 'LIEUT', name: 'SURESH KUMAR', regiment: 'SIKH' },
{ rank: 'LIEUT', name: 'RAJIV SHARMA', regiment: 'ASSAM' },
{ rank: 'MAJ', name: 'AMIT SINGH', regiment: 'RIFLES' },
{ rank: 'CAPT', name: 'RAVI KUMAR', regiment: 'JAT' },
{ rank: 'MAJ', name: 'RAJEEV KUMAR', regiment: 'ARMY' },
{ rank: 'SEP', name: 'ANIL KUMAR', regiment: 'SIKH LI' },
{ rank: 'NAIK', name: 'RAVINDER SINGH', regiment: 'PUNJAB' },
{ rank: 'LIEUT', name: 'DINESH KUMAR', regiment: 'GORKHA' },
{ rank: 'NAIK', name: 'RAVINDER KUMAR', regiment: 'ASSAM' },
{ rank: 'CAPT', name: 'SURESH KUMAR', regiment: 'RAJPUT' },
{ rank: 'SEP', name: 'RAVI SINGH', regiment: 'SIKH' },
{ rank: 'LIEUT', name: 'GURMEET SINGH', regiment: 'JAT' },
{ rank: 'LIEUT', name: 'SUSHIL KUMAR', regiment: 'BENGAL ENGINEERS' },
{ rank: 'SEP', name: 'SURESH KUMAR', regiment: 'RAJPUT' },
{ rank: 'NAIK', name: 'BALJIT SINGH', regiment: 'SIKH' },
{ rank: 'MAJ', name: 'JASBIR SINGH', regiment: 'RAJPUT' },
{ rank: 'LIEUT', name: 'KULDEEP SINGH', regiment: 'GORKHA' },
{ rank: 'CAPT', name: 'JAGDEEP SINGH', regiment: 'RIFLES' },
{ rank: 'NAIK', name: 'RAM KUMAR', regiment: 'JAT' },
{ rank: 'SEP', name: 'MOHIT KUMAR', regiment: 'SIKH' },
{ rank: 'LIEUT', name: 'RANJEET SINGH', regiment: 'BENGAL ENGINEERS' },
{ rank: 'CAPT', name: 'VIJAY KUMAR', regiment: 'ARMY' },
{ rank: 'SEP', name: 'RAJESH KUMAR', regiment: 'SIKH LI' },
{ rank: 'NAIK', name: 'ANIL SINGH', regiment: 'RAJPUT' },
{ rank: 'LIEUT', name: 'RAJIV KUMAR', regiment: 'PUNJAB' },
{ rank: 'MAJ', name: 'SANTOSH KUMAR', regiment: 'RIFLES' },
{ rank: 'SEP', name: 'PRADEEP KUMAR', regiment: 'SIKH' },
{ rank: 'CAPT', name: 'VIKRAM SINGH', regiment: 'GORKHA' },
{ rank: 'NAIK', name: 'SACHIN KUMAR', regiment: 'ARMY' },
{ rank: 'SEP', name: 'RAJ KUMAR', regiment: 'PUNJAB' },
{ rank: 'LIEUT', name: 'JAGPREET SINGH', regiment: 'JAT' },
{ rank: 'MAJ', name: 'RAVI SHANKAR', regiment: 'GORKHA' },
{ rank: 'CAPT', name: 'YOGESH KUMAR', regiment: 'ASSAM' },
{ rank: 'LIEUT', name: 'RAMESH KUMAR', regiment: 'PUNJAB' },
{ rank: 'NAIK', name: 'SURESH KUMAR', regiment: 'RAJPUT' },
{ rank: 'SEP', name: 'RAKESH KUMAR', regiment: 'JAT' },
{ rank: 'NAIK', name: 'PRADEEP KUMAR', regiment: 'SIKH' },
{ rank: 'LIEUT', name: 'HARPREET SINGH', regiment: 'RAJPUT' },
{ rank: 'CAPT', name: 'RAVI KUMAR', regiment: 'ARMY' },
{ rank: 'SEP', name: 'KARAM SINGH', regiment: 'JAT' },
{ rank: 'NAIK', name: 'BALKAR SINGH', regiment: 'PUNJAB' },
{ rank: 'CAPT', name: 'AMARJIT SINGH', regiment: 'RAJPUT' },
{ rank: 'LIEUT', name: 'NAVDEEP SINGH', regiment: 'SIKH' },
{ rank: 'MAJ', name: 'SANDEEP KUMAR', regiment: 'RIFLES' },
{ rank: 'SEP', name: 'KULDEEP SINGH', regiment: 'JAT' },
{ rank: 'LIEUT', name: 'SAVITRI DEVI', regiment: 'ASSAM' },
{ rank: 'CAPT', name: 'SURESH KUMAR', regiment: 'SIKH LI' },
{ rank: 'NAIK', name: 'RAVI KUMAR', regiment: 'GORKHA' },
{ rank: 'SEP', name: 'RAMAN KUMAR', regiment: 'PUNJAB' },
{ rank: 'LIEUT', name: 'HARPREET KAUR', regiment: 'RAJPUT' },
{ rank: 'MAJ', name: 'RAVI KUMAR', regiment: 'PUNJAB' },
{ rank: 'CAPT', name: 'RAJINDER SINGH', regiment: 'RAJPUT' },
{ rank: 'NAIK', name: 'MANOJ KUMAR', regiment: 'JAT' },
{ rank: 'SEP', name: 'VISHAL KUMAR', regiment: 'SIKH' },
{ rank: 'LIEUT', name: 'RITIKA SHARMA', regiment: 'GORKHA' },
{ rank: 'CAPT', name: 'RAJESH KUMAR', regiment: 'RIFLES' },
{ rank: 'NAIK', name: 'PRADEEP SINGH', regiment: 'BENGAL ENGINEERS' },
{ rank: 'SEP', name: 'MOHAN SINGH', regiment: 'SIKH LI' },
{ rank: 'LIEUT', name: 'PRIYA SINGH', regiment: 'PUNJAB' },
{ rank: 'CAPT', name: 'PRAVEEN KUMAR', regiment: 'JAT' },
{ rank: 'NAIK', name: 'MANOJ SINGH', regiment: 'SIKH' },
{ rank: 'SEP', name: 'VIKASH KUMAR', regiment: 'PUNJAB' },
{ rank: 'LIEUT', name: 'HARJINDER SINGH', regiment: 'RAJPUT' },
{ rank: 'CAPT', name: 'GURPREET SINGH', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'NAIK', name: 'HARPREET KUMAR', regiment: 'BENGAL ENGINEERS' },
{ rank: 'SEP', name: 'RAVI SHANKAR', regiment: 'JAT' },
{ rank: 'LIEUT', name: 'AMANDEEP SINGH', regiment: 'SIKH' },
{ rank: 'CAPT', name: 'VIKRAM SINGH', regiment: 'PUNJAB' },
{ rank: 'NAIK', name: 'ARVIND KUMAR', regiment: 'SIKH' },
{ rank: 'SEP', name: 'JASPREET SINGH', regiment: 'RAJPUT' },
{ rank: 'LIEUT', name: 'KAMLESH KUMAR', regiment: 'GORKHA' },
{ rank: 'CAPT', name: 'RUPINDER SINGH', regiment: 'ASSAM' },
{ rank: 'NAIK', name: 'SHIV KUMAR', regiment: 'RAJPUT' },
{ rank: 'SEP', name: 'RATAN SINGH', regiment: 'PUNJAB' },
{ rank: 'LIEUT', name: 'VANDANA SHARMA', regiment: 'RAJPUT' },
{ rank: 'CAPT', name: 'GURPREET KUMAR', regiment: 'SIKH' },
{ rank: 'NAIK', name: 'JAGDISH SINGH', regiment: 'RIFLES' },
{ rank: 'SEP', name: 'SANTOSH KUMAR', regiment: 'PUNJAB' },
{ rank: 'LIEUT', name: 'RAVI SINGH', regiment: 'JAT' },
{ rank: 'CAPT', name: 'ANSHUL KUMAR', regiment: 'RAJPUT' },
{ rank: 'NAIK', name: 'VIKASH KUMAR', regiment: 'ASSAM' },
{ rank: 'SEP', name: 'BALJIT SINGH', regiment: 'JAT' },
{ rank: 'LIEUT', name: 'AMRIT KAUR', regiment: 'PUNJAB' },
{ rank: 'CAPT', name: 'RAGHAV KUMAR', regiment: 'SIKH' },
{ rank: 'NAIK', name: 'MUKESH KUMAR', regiment: 'BENGAL ENGINEERS' },
{ rank: 'SEP', name: 'SUDHIR SINGH', regiment: 'JAT' },
{ rank: 'LIEUT', name: 'GURPREET SINGH', regiment: 'RAJPUT' },
{ rank: 'CAPT', name: 'RAJINDER SINGH', regiment: 'RIFLES' },
{ rank: 'NAIK', name: 'RAJESH KUMAR', regiment: 'SIKH' },
{ rank: 'SEP', name: 'PANKAJ KUMAR', regiment: 'RAJPUT' },
{ rank: 'LIEUT', name: 'SNEHA SINGH', regiment: 'JAT' },
{ rank: 'CAPT', name: 'SUNITA KUMAR', regiment: 'SIKH' },
{ rank: 'NAIK', name: 'SANJAY KUMAR', regiment: 'BENGAL ENGINEERS' },
{ rank: 'SEP', name: 'JOGINDER SINGH', regiment: 'RAJPUT' },
{ rank: 'LIEUT', name: 'RAVI KUMAR', regiment: 'ASSAM' },
{ rank: 'CAPT', name: 'DEEPAK SINGH', regiment: 'RAJPUT' },
{ rank: 'NAIK', name: 'RAMESH KUMAR', regiment: 'JAT' },
{ rank: 'SEP', name: 'NARINDER SINGH', regiment: 'SIKH' },
{ rank: 'LIEUT', name: 'HARJIT SINGH', regiment: 'RAJPUT' },
{ rank: 'CAPT', name: 'AMIT KUMAR', regiment: 'RIFLES' },
{ rank: 'NAIK', name: 'SANJAY SINGH', regiment: 'PUNJAB' },
{ rank: 'SEP', name: 'SURESH KUMAR', regiment: 'ASSAM' },
{ rank: 'LIEUT', name: 'PRIYA SHARMA', regiment: 'RAJPUT' },
{ rank: 'CAPT', name: 'RAKESH SINGH', regiment: 'BENGAL ENGINEERS' },
{ rank: 'NAIK', name: 'RAVI KUMAR', regiment: 'JAT' },
{ rank: 'SEP', name: 'MOHIT SINGH', regiment: 'SIKH' },
{ rank: 'LIEUT', name: 'SUMIT KUMAR', regiment: 'PUNJAB' },
{ rank: 'CAPT', name: 'SUNIL SINGH', regiment: 'RAJPUT' },
{ rank: 'NAIK', name: 'DINESH KUMAR', regiment: 'RAJPUT' },
{ rank: 'SEP', name: 'JAI KUMAR', regiment: 'JAT' },
{ rank: 'LIEUT', name: 'AMARJEET SINGH', regiment: 'SIKH' },
{ rank: 'CAPT', name: 'VIVEK SINGH', regiment: 'ASSAM' },
{ rank: 'NAIK', name: 'RAJINDER KUMAR', regiment: 'RIFLES' },
{ rank: 'SEP', name: 'INDRANIL KUMAR', regiment: 'BENGAL ENGINEERS' },
{ rank: 'LIEUT', name: 'NARENDRA SINGH', regiment: 'RAJPUT' },
{ rank: 'CAPT', name: 'RAHUL SHARMA', regiment: 'JAT' },
{ rank: 'NAIK', name: 'RAJEEV KUMAR', regiment: 'SIKH' },
{ rank: 'SEP', name: 'DEVENDER SINGH', regiment: 'PUNJAB' },
{ rank: 'LIEUT', name: 'SUNITA KUMAR', regiment: 'ASSAM' },
{ rank: 'CAPT', name: 'SANDEEP SINGH', regiment: 'RAJPUT' },
{ rank: 'NAIK', name: 'SHUBHAM KUMAR', regiment: 'RAJPUT' },
{ rank: 'SEP', name: 'GURPREET KUMAR', regiment: 'JAT' },
{ rank: 'LIEUT', name: 'SHIVANI SINGH', regiment: 'RAJPUT' },
{ rank: 'CAPT', name: 'TARUN SINGH', regiment: 'PUNJAB' },
{ rank: 'NAIK', name: 'MANOJ KUMAR', regiment: 'SIKH' },
{ rank: 'SEP', name: 'RAKESH KUMAR', regiment: 'RAJPUT' },
{ rank: 'LIEUT', name: 'AMIT SINGH', regiment: 'BENGAL ENGINEERS' },
{ rank: 'CAPT', name: 'BALWINDER SINGH', regiment: 'RAJPUT' },
{ rank: 'NAIK', name: 'TARUN KUMAR', regiment: 'ASSAM' },
{ rank: 'SEP', name: 'SUSHIL KUMAR', regiment: 'JAT' },
{ rank: 'LIEUT', name: 'PRADEEP SINGH', regiment: 'SIKH' },
{ rank: 'CAPT', name: 'KARAMJEET SINGH', regiment: 'RAJPUT' },
{ rank: 'NAIK', name: 'GURMUKH SINGH', regiment: 'RAJPUT' },
{ rank: 'SEP', name: 'SANDEEP KUMAR', regiment: 'RAJPUT' },
{ rank: 'LIEUT', name: 'JATINDER SINGH', regiment: 'SIKH' },
{ rank: 'CAPT', name: 'AMIT KUMAR', regiment: 'ASSAM' },
{ rank: 'NAIK', name: 'PANKAJ SINGH', regiment: 'RAJPUT' },
{ rank: 'SEP', name: 'DEEPAK KUMAR', regiment: 'BENGAL ENGINEERS' },
{ rank: 'LIEUT', name: 'NAVDEEP SINGH', regiment: 'RAJPUT' },
{ rank: 'CAPT', name: 'HARIOM SINGH', regiment: 'JAT' },
{ rank: 'NAIK', name: 'RAVI SHARMA', regiment: 'RAJPUT' },
{ rank: 'SEP', name: 'JAGDEEP KUMAR', regiment: 'PUNJAB' },
{ rank: 'LIEUT', name: 'GURPREET SINGH', regiment: 'SIKH' },
{ rank: 'CAPT', name: 'RAKESH KUMAR', regiment: 'JAT' },
{ rank: 'NAIK', name: 'AMANDEEP SINGH', regiment: 'RAJPUT' },
{ rank: 'SEP', name: 'MUKESH SINGH', regiment: 'PUNJAB' },
{ rank: 'LIEUT', name: 'HARPREET SINGH', regiment: 'ASSAM' },
{ rank: 'CAPT', name: 'SANJAY SINGH', regiment: 'RAJPUT' },
{ rank: 'NAIK', name: 'VIRENDER KUMAR', regiment: 'JAT' },
{ rank: 'SEP', name: 'VIKRAM SINGH', regiment: 'SIKH' },
{ rank: 'LIEUT', name: 'MANPREET SINGH', regiment: 'BENGAL ENGINEERS' },
{ rank: 'CAPT', name: 'RAM KUMAR', regiment: 'RAJPUT' },
{ rank: 'NAIK', name: 'DEVINDER KUMAR', regiment: 'ASSAM' },
{ rank: 'SEP', name: 'MOHIT KUMAR', regiment: 'RAJPUT' },
{ rank: 'LIEUT', name: 'GURJEET SINGH', regiment: 'SIKH' },
{ rank: 'CAPT', name: 'AJAY KUMAR', regiment: 'RAJPUT' },
{ rank: 'NAIK', name: 'PRAVEEN KUMAR', regiment: 'PUNJAB' },
{ rank: 'SEP', name: 'SURINDER SINGH', regiment: 'JAT' },
{ rank: 'LIEUT', name: 'RAVINDER SINGH', regiment: 'RAJPUT' },
{ rank: 'CAPT', name: 'VINOD KUMAR', regiment: 'ASSAM' },
{ rank: 'NAIK', name: 'SANDEEP KUMAR', regiment: 'RAJPUT' },
{ rank: 'SEP', name: 'PRAKASH SINGH', regiment: 'SIKH' },
{ rank: 'LIEUT', name: 'BALJIT SINGH', regiment: 'RAJPUT' },
{ rank: 'CAPT', name: 'KAMAL KUMAR', regiment: 'PUNJAB' },
{ rank: 'NAIK', name: 'RAJ KUMAR', regiment: 'ASSAM' },
{ rank: 'SEP', name: 'JASWINDER SINGH', regiment: 'RAJPUT' },
{ rank: 'LIEUT', name: 'KULDEEP SINGH', regiment: 'RAJPUT' },
{ rank: 'CAPT', name: 'RAM AVTAR', regiment: 'JAT' },
{ rank: 'NAIK', name: 'MANISH SINGH', regiment: 'SIKH' },
{ rank: 'SEP', name: 'GULSHAN KUMAR', regiment: 'RAJPUT' },
{ rank: 'LIEUT', name: 'MOHIT SINGH', regiment: 'BENGAL ENGINEERS' },
{ rank: 'CAPT', name: 'ANIL KUMAR', regiment: 'RAJPUT' },
{ rank: 'NAIK', name: 'DINESH SINGH', regiment: 'JAT' },
{ rank: 'SEP', name: 'RAVI KUMAR', regiment: 'PUNJAB' },
{ rank: 'LIEUT', name: 'PUNIT SINGH', regiment: 'ASSAM' },
{ rank: 'CAPT', name: 'SANTOSH KUMAR', regiment: 'RAJPUT' },
{ rank: 'NAIK', name: 'RAVI CHANDER', regiment: 'SIKH' },
{ rank: 'SEP', name: 'VIJAY SINGH', regiment: 'RAJPUT' },
{ rank: 'LIEUT', name: 'KULDEEP SINGH', regiment: 'BENGAL ENGINEERS' },
{ rank: 'CAPT', name: 'RAMESH KUMAR', regiment: 'PUNJAB' },
{ rank: 'NAIK', name: 'BIR SINGH', regiment: 'ASSAM' },
{ rank: 'SEP', name: 'PARAMJIT SINGH', regiment: 'JAT' },
{ rank: 'LIEUT', name: 'JASWINDER SINGH', regiment: 'RAJPUT' },
{ rank: 'CAPT', name: 'ARUN KUMAR', regiment: 'RAJPUT' },
{ rank: 'NAIK', name: 'HARMINDER SINGH', regiment: 'SIKH' },
{ rank: 'SEP', name: 'RAJINDER SINGH', regiment: 'RAJPUT' },
{ rank: 'LIEUT', name: 'INDER SINGH', regiment: 'RAJPUT' },
{ rank: 'CAPT', name: 'VIRINDER KUMAR', regiment: 'RAJPUT' },
{ rank: 'NAIK', name: 'JAI SINGH', regiment: 'ASSAM' },
{ rank: 'SEP', name: 'DEVENDER SINGH', regiment: 'PUNJAB' },
{ rank: 'LIEUT', name: 'AMIT SINGH', regiment: 'RAJPUT' },
{ rank: 'CAPT', name: 'PUNIT KUMAR', regiment: 'BENGAL ENGINEERS' },
{ rank: 'NAIK', name: 'LALIT SINGH', regiment: 'RAJPUT' },
{ rank: 'SEP', name: 'SANTOSH SINGH', regiment: 'JAT' },
{ rank: 'LIEUT', name: 'RAJINDER KUMAR', regiment: 'ASSAM' },
{ rank: 'CAPT', name: 'MAHINDER SINGH', regiment: 'SIKH' },
{ rank: 'NAIK', name: 'KISHORE KUMAR', regiment: 'PUNJAB' },
{ rank: 'SEP', name: 'TEJINDER SINGH', regiment: 'RAJPUT' },
{ rank: 'LIEUT', name: 'ROHIT KUMAR', regiment: 'RAJPUT' },
{ rank: 'CAPT', name: 'MAHESH KUMAR', regiment: 'JAT' },
{ rank: 'NAIK', name: 'RAVI SHARMA', regiment: 'RAJPUT' },
{ rank: 'SEP', name: 'SURESH KUMAR', regiment: 'SIKH' },
{ rank: 'LIEUT', name: 'INDERJIT SINGH', regiment: 'PUNJAB' },
{ rank: 'CAPT', name: 'KUNAL SINGH', regiment: 'RAJPUT' },
{ rank: 'NAIK', name: 'NARESH SINGH', regiment: 'ASSAM' },
{ rank: 'SEP', name: 'BALJIT KUMAR', regiment: 'RAJPUT' },
{ rank: 'LIEUT', name: 'SURENDER SINGH', regiment: 'RAJPUT' },
{ rank: 'CAPT', name: 'GURVINDER SINGH', regiment: 'SIKH' },
{ rank: 'NAIK', name: 'VIRENDER KUMAR', regiment: 'PUNJAB' },
{ rank: 'SEP', name: 'VIKASH KUMAR', regiment: 'RAJPUT' },
{ rank: 'LIEUT', name: 'RAVI SINGH', regiment: 'RAJPUT' },
{ rank: 'CAPT', name: 'AMIT KUMAR', regiment: 'JAT' },
{ rank: 'NAIK', name: 'GURPREET SINGH', regiment: 'SIKH' },
{ rank: 'SEP', name: 'RAJESH KUMAR', regiment: 'RAJPUT' },
{ rank: 'LIEUT', name: 'VIKASH SINGH', regiment: 'PUNJAB' },
{ rank: 'CAPT', name: 'DEEPAK SINGH', regiment: 'RAJPUT' },
{ rank: 'NAIK', name: 'GURVINDER SINGH', regiment: 'ASSAM' },
{ rank: 'SEP', name: 'MANOJ KUMAR', regiment: 'RAJPUT' },
{ rank: 'LIEUT', name: 'PREM SINGH', regiment: 'PUNJAB' },
{ rank: 'CAPT', name: 'JAI KUMAR', regiment: 'SIKH' },
{ rank: 'NAIK', name: 'RAVINDER SINGH', regiment: 'RAJPUT' },
{ rank: 'SEP', name: 'SURESH KUMAR', regiment: 'ASSAM' },
{ rank: 'LIEUT', name: 'NARINDER KUMAR', regiment: 'RAJPUT' },
{ rank: 'CAPT', name: 'AMAR SINGH', regiment: 'PUNJAB' },
{ rank: 'NAIK', name: 'NITIN SINGH', regiment: 'RAJPUT' },
{ rank: 'SEP', name: 'RAKESH KUMAR', regiment: 'JAT' },
{ rank: 'LIEUT', name: 'VIRENDER SINGH', regiment: 'RAJPUT' },
{ rank: 'CAPT', name: 'SHAM SINGH', regiment: 'SIKH' },
{ rank: 'NAIK', name: 'VIKRAM SINGH', regiment: 'RAJPUT' },
{ rank: 'SEP', name: 'SANTOSH KUMAR', regiment: 'PUNJAB' },
{ rank: 'LIEUT', name: 'JAGJIT SINGH', regiment: 'ASSAM' },
{ rank: 'CAPT', name: 'MOHAN SINGH', regiment: 'RAJPUT' },
{ rank: 'NAIK', name: 'ANIL KUMAR', regiment: 'SIKH' },
{ rank: 'SEP', name: 'KULDEEP SINGH', regiment: 'PUNJAB' },
{ rank: 'LIEUT', name: 'RANJEET SINGH', regiment: 'RAJPUT' },
{ rank: 'CAPT', name: 'GURPREET KUMAR', regiment: 'RAJPUT' },
{ rank: 'NAIK', name: 'MAHENDER SINGH', regiment: 'SIKH' },
{ rank: 'SEP', name: 'SURENDER KUMAR', regiment: 'ASSAM' },
{ rank: 'LIEUT', name: 'JAGMEET SINGH', regiment: 'PUNJAB' },
{ rank: 'CAPT', name: 'PRAVIN SINGH', regiment: 'RAJPUT' },
{ rank: 'NAIK', name: 'SUKHDEV SINGH', regiment: 'RAJPUT' },
{ rank: 'SEP', name: 'KARAMJEET SINGH', regiment: 'SIKH' },
{ rank: 'LIEUT', name: 'NARESH KUMAR', regiment: 'RAJPUT' },
{ rank: 'CAPT', name: 'LOKESH SINGH', regiment: 'JAT' },
{ rank: 'NAIK', name: 'RAJINDER SINGH', regiment: 'RAJPUT' },
{ rank: 'SEP', name: 'BISWAJIT SINGH', regiment: 'RAJPUT' },
{ rank: 'LIEUT', name: 'SUKHWINDER SINGH', regiment: 'ASSAM' },
{ rank: 'CAPT', name: 'SUNIL KUMAR', regiment: 'SIKH' },
{ rank: 'NAIK', name: 'RUPINDER SINGH', regiment: 'RAJPUT' },
{ rank: 'SEP', name: 'DEVENDER SINGH', regiment: 'PUNJAB' },
{ rank: 'LIEUT', name: 'GAGANDEEP SINGH', regiment: 'RAJPUT' },
{ rank: 'CAPT', name: 'HARMINDER SINGH', regiment: 'SIKH' },
{ rank: 'NAIK', name: 'RAKESH KUMAR', regiment: 'ASSAM' },
{ rank: 'SEP', name: 'JASWINDER SINGH', regiment: 'RAJPUT' },
{ rank: 'LIEUT', name: 'SHIVRAJ SINGH', regiment: 'PUNJAB' },
{ rank: 'CAPT', name: 'AMRENDER SINGH', regiment: 'SIKH' },
{ rank: 'NAIK', name: 'RAVI KUMAR', regiment: 'RAJPUT' },
{ rank: 'SEP', name: 'RANVIR SINGH', regiment: 'PUNJAB' },
{ rank: 'LIEUT', name: 'MOHIT SINGH', regiment: 'RAJPUT' },
{ rank: 'CAPT', name: 'SHAILENDER KUMAR', regiment: 'ASSAM' },
{ rank: 'NAIK', name: 'PRADEEP SINGH', regiment: 'SIKH' },
{ rank: 'SEP', name: 'VIKASH KUMAR', regiment: 'RAJPUT' },
{ rank: 'LIEUT', name: 'SANDEEP SINGH', regiment: 'PUNJAB' },
{ rank: 'CAPT', name: 'ARJUN SINGH', regiment: 'SIKH' },
{ rank: 'NAIK', name: 'AMIT SINGH', regiment: 'RAJPUT' },
{ rank: 'SEP', name: 'NARESH SINGH', regiment: 'RAJPUT' },
{ rank: 'LIEUT', name: 'HARJINDER SINGH', regiment: 'ASSAM' },
{ rank: 'CAPT', name: 'MAHENDER KUMAR', regiment: 'PUNJAB' },
{ rank: 'NAIK', name: 'BIR SINGH', regiment: 'RAJPUT' },
{ rank: 'SEP', name: 'KARAN SINGH', regiment: 'SIKH' },
{ rank: 'LIEUT', name: 'NAVDEEP SINGH', regiment: 'PUNJAB' },
{ rank: 'CAPT', name: 'TEJINDER SINGH', regiment: 'RAJPUT' },
{ rank: 'NAIK', name: 'VIRENDER KUMAR', regiment: 'SIKH' },
{ rank: 'SEP', name: 'KULDEEP KUMAR', regiment: 'RAJPUT' },
{ rank: 'LIEUT', name: 'SUNITA SINGH', regiment: 'ASSAM' },
{ rank: 'CAPT', name: 'RATAN SINGH', regiment: 'PUNJAB' },
{ rank: 'NAIK', name: 'NARINDER SINGH', regiment: 'RAJPUT' },
{ rank: 'SEP', name: 'PRAKASH SINGH', regiment: 'RAJPUT' },
{ rank: 'LIEUT', name: 'YOGINDER SINGH', regiment: 'RAJPUT' },
{ rank: 'CAPT', name: 'HARMANDEEP SINGH', regiment: 'SIKH' },
{ rank: 'NAIK', name: 'SHAMINDER SINGH', regiment: 'RAJPUT' },
{ rank: 'SEP', name: 'PINKI DEVI', regiment: 'RAJPUT' },
{ rank: 'LIEUT', name: 'GURBIR SINGH', regiment: 'ASSAM' },
{ rank: 'CAPT', name: 'MUKESH KUMAR', regiment: 'RAJPUT' },
{ rank: 'NAIK', name: 'VINOD SINGH', regiment: 'SIKH' },
{ rank: 'SEP', name: 'RAJESH KUMAR', regiment: 'PUNJAB' },
{ rank: 'SEP', name: 'RAMESH KUMAR', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'VIKRAM SINGH', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'RAVI KUMAR', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'NAVEEN KUMAR', regiment: 'BENGAL ENGINEERS' },
{ rank: 'SEP', name: 'AJAY KUMAR', regiment: 'MARCOS' },
{ rank: 'SEP', name: 'MANOJ KUMAR', regiment: 'SOUTHERN COMMAND' },
{ rank: 'SEP', name: 'ALOK YADAV', regiment: 'RAPID ACTION FORCE' },
{ rank: 'SEP', name: 'RAJESH KUMAR', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'SATISH KUMAR', regiment: 'SCO' },
{ rank: 'SEP', name: 'ROHIT KUMAR', regiment: 'SABRE COMMAND' },
{ rank: 'SEP', name: 'SANJEEV KUMAR', regiment: '8 PARA' },
{ rank: 'SEP', name: 'PANKAJ SINGH', regiment: '9 PARA SF' },
{ rank: 'SEP', name: 'AJAY KUMAR', regiment: 'RAPID ACTION FORCE' },
{ rank: 'SEP', name: 'JAI KUMAR', regiment: 'INS KALPANA' },
{ rank: 'SEP', name: 'ARVIND KUMAR', regiment: 'BSF' },
{ rank: 'SEP', name: 'VIVEK SINGH', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'SUSHIL KUMAR', regiment: 'BSF' },
{ rank: 'SEP', name: 'HARIOM KUMAR', regiment: 'MARCOS' },
{ rank: 'SEP', name: 'SOMNATH', regiment: 'GORKHA REGIMENT' },
{ rank: 'SEP', name: 'PRAKASH KUMAR', regiment: 'SABRE COMMAND' },
{ rank: 'SEP', name: 'VINOD KUMAR', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'GULAB SINGH', regiment: 'BENGAL ENGINEERS' },
{ rank: 'SEP', name: 'KISHOR KUMAR', regiment: 'SOUTHERN COMMAND' },
{ rank: 'SEP', name: 'BASANT KUMAR', regiment: 'MECH INFANTRY' },
{ rank: 'SEP', name: 'MOHAN SINGH', regiment: '9 PARA SF' },
{ rank: 'SEP', name: 'RAJENDER KUMAR', regiment: 'MARINE COMMANDO' },
{ rank: 'SEP', name: 'RAMESH SINGH', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'BIR SINGH', regiment: 'GORKHA REGIMENT' },
{ rank: 'SEP', name: 'RAVI SINGH', regiment: 'MECH INFANTRY' },
{ rank: 'SEP', name: 'ANAND KUMAR', regiment: 'MARCOS' },
{ rank: 'SEP', name: 'SHANKAR KUMAR', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'VIKRAMJIT SINGH', regiment: 'SCO' },
{ rank: 'SEP', name: 'SURESH SINGH', regiment: 'BENGAL ENGINEERS' },
{ rank: 'SEP', name: 'BALWINDER SINGH', regiment: 'INS KALPANA' },
{ rank: 'SEP', name: 'SANDEEP KUMAR', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'PAWAN KUMAR', regiment: '8 PARA' },
{ rank: 'SEP', name: 'RAHUL KUMAR', regiment: 'SOUTHERN COMMAND' },
{ rank: 'SEP', name: 'MANOJ KUMAR', regiment: 'SCO' },
{ rank: 'SEP', name: 'RAVI KUMAR', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'MUKESH SINGH', regiment: 'GORKHA REGIMENT' },
{ rank: 'SEP', name: 'SANJAY KUMAR', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'VIKAS KUMAR', regiment: 'MARCOS' },
{ rank: 'SEP', name: 'ROHIT KUMAR', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'PRAKASH SINGH', regiment: 'BENGAL ENGINEERS' },
{ rank: 'SEP', name: 'DEVENDER KUMAR', regiment: '8 PARA' },
{ rank: 'SEP', name: 'ASHOK KUMAR', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'RATAN KUMAR', regiment: 'SABRE COMMAND' },
{ rank: 'SEP', name: 'SURESH KUMAR', regiment: 'MARINE COMMANDO' },
{ rank: 'SEP', name: 'SANTOSH KUMAR', regiment: 'INS KALPANA' },
{ rank: 'SEP', name: 'MANOJ KUMAR', regiment: 'BSF' },
{ rank: 'SEP', name: 'AMIT SINGH', regiment: 'SOUTHERN COMMAND' },
{ rank: 'SEP', name: 'VIRENDER SINGH', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'BIR SINGH', regiment: 'MECH INFANTRY' },
{ rank: 'SEP', name: 'RAVI KUMAR', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'ANIL KUMAR', regiment: 'MARCOS' },
{ rank: 'SEP', name: 'RAJINDER KUMAR', regiment: '9 PARA SF' },
{ rank: 'SEP', name: 'SUNITA RANI', regiment: 'SCO' },
{ rank: 'SEP', name: 'DEEPAK SINGH', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'PRAVEEN KUMAR', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'RAKESH KUMAR', regiment: 'GORKHA REGIMENT' },
{ rank: 'SEP', name: 'RAM KUMAR', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'MOHAN SINGH', regiment: 'INS KALPANA' },
{ rank: 'SEP', name: 'VIKRAM SINGH', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'JAI KUMAR', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'RAVI SINGH', regiment: 'GORKHA REGIMENT' },
{ rank: 'SEP', name: 'HARIOM SINGH', regiment: '8 PARA' },
{ rank: 'SEP', name: 'AMIT KUMAR', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'SHAMSHER SINGH', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'PAWAN KUMAR', regiment: 'BSF' },
{ rank: 'SEP', name: 'MANOJ KUMAR', regiment: 'SABRE COMMAND' },
{ rank: 'SEP', name: 'ROHIT KUMAR', regiment: 'MARINE COMMANDO' },
{ rank: 'SEP', name: 'RAJESH SINGH', regiment: 'SCO' },
{ rank: 'SEP', name: 'JATINDER SINGH', regiment: 'GORKHA REGIMENT' },
{ rank: 'SEP', name: 'PANKAJ KUMAR', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'BIR SINGH', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'DINESH KUMAR', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'RAVI KUMAR', regiment: 'MARCO' },
{ rank: 'SEP', name: 'RAKESH KUMAR', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'HARNAM SINGH', regiment: 'MECH INFANTRY' },
{ rank: 'SEP', name: 'MANOJ KUMAR', regiment: 'SOUTHERN COMMAND' },
{ rank: 'SEP', name: 'JAGDISH KUMAR', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'PANKAJ SINGH', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'SURESH KUMAR', regiment: 'GORKHA REGIMENT' },
{ rank: 'SEP', name: 'VIKRAM SINGH', regiment: 'MARCOS' },
{ rank: 'SEP', name: 'DEVENDER SINGH', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'RAVI SINGH', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'SANTOSH SINGH', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'SURESH KUMAR', regiment: 'INS KALPANA' },
{ rank: 'SEP', name: 'RAJINDER KUMAR', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'VIRENDER KUMAR', regiment: 'BSF' },
{ rank: 'SEP', name: 'RAKESH KUMAR', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'AMIT SINGH', regiment: 'GORKHA REGIMENT' },
{ rank: 'SEP', name: 'MANOJ KUMAR', regiment: 'INS KALPANA' },
{ rank: 'SEP', name: 'SANTOSH KUMAR', regiment: 'SABRE COMMAND' },
{ rank: 'SEP', name: 'HARI SINGH', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'RAJESH KUMAR', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'KULDEEP KUMAR', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'DEEPAK SINGH', regiment: 'MARINE COMMANDO' },
{ rank: 'SEP', name: 'MANOJ KUMAR', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'VIKRAM KUMAR', regiment: 'SCO' },
{ rank: 'SEP', name: 'RAKESH KUMAR', regiment: 'GORKHA REGIMENT' },
{ rank: 'SEP', name: 'HIMANSHU SINGH', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'SANJEEV KUMAR', regiment: 'SABRE COMMAND' },
{ rank: 'SEP', name: 'ASHOK SINGH', regiment: 'MARINE COMMANDO' },
{ rank: 'SEP', name: 'SURESH KUMAR', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'RAVI KUMAR', regiment: 'INS KALPANA' },
{ rank: 'SEP', name: 'RAJINDER SINGH', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'DEVINDER KUMAR', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'SHAMSHER SINGH', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'ANIL KUMAR', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'RATAN SINGH', regiment: 'GORKHA REGIMENT' },
{ rank: 'SEP', name: 'MOHAN KUMAR', regiment: 'MARINE COMMANDO' },
{ rank: 'SEP', name: 'RAJESH KUMAR', regiment: 'SABRE COMMAND' },
{ rank: 'SEP', name: 'RAVI KUMAR', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'MANOJ SINGH', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'SANTOSH KUMAR', regiment: 'GORKHA REGIMENT' },
{ rank: 'SEP', name: 'ASHOK KUMAR', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'PANKAJ SINGH', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'RAVI SINGH', regiment: 'GORKHA REGIMENT' },
{ rank: 'SEP', name: 'RAKESH KUMAR', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'HARIOM SINGH', regiment: 'INS KALPANA' },
{ rank: 'SEP', name: 'SANJAY SINGH', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'RAVI KUMAR', regiment: 'MARINE COMMANDO' },
{ rank: 'SEP', name: 'ROHIT KUMAR', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'SURESH KUMAR', regiment: 'INS KALPANA' },
{ rank: 'SEP', name: 'RAJINDER KUMAR', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'SHIV KUMAR', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'KULDEEP SINGH', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'RAJESH SINGH', regiment: 'GORKHA REGIMENT' },
{ rank: 'SEP', name: 'VIKRAM SINGH', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'AMIT KUMAR', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'RAVI KUMAR', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'VIRENDER SINGH', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'RAJINDER KUMAR', regiment: 'GORKHA REGIMENT' },
{ rank: 'SEP', name: 'MANOJ KUMAR', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'HARIOM SINGH', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'SHAMSHER SINGH', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'SURESH KUMAR', regiment: 'GORKHA REGIMENT' },
{ rank: 'SEP', name: 'PANKAJ KUMAR', regiment: 'INS KALPANA' },
{ rank: 'SEP', name: 'RAJINDER SINGH', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'MANOJ SINGH', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'ASHOK SINGH', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'DEVENDER KUMAR', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'HARIOM KUMAR', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'RATAN SINGH', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'VIKRAM KUMAR', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'RAJESH KUMAR', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'SANJEEV SINGH', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'VIRENDER SINGH', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'HIMANSHU SINGH', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'RAKESH KUMAR', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'DEVINDER SINGH', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'MANOJ KUMAR', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'AMIT KUMAR', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'RAJINDER SINGH', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'SANTOSH KUMAR', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'RAJESH SINGH', regiment: 'GORKHA REGIMENT' },
{ rank: 'SEP', name: 'SHIV SINGH', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'KULDEEP KUMAR', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'VIKRAM SINGH', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'JAGDISH SINGH', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'SURESH SINGH', regiment: 'GORKHA REGIMENT' },
{ rank: 'SEP', name: 'DEVENDER SINGH', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'RAKESH SINGH', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'PANKAJ SINGH', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'MANOJ SINGH', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'VIRENDER KUMAR', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'RAJESH KUMAR', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'RAJINDER KUMAR', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'HARIOM SINGH', regiment: 'GORKHA REGIMENT' },
{ rank: 'SEP', name: 'ASHOK KUMAR', regiment: 'INS KALPANA' },
{ rank: 'SEP', name: 'SANTOSH KUMAR', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'RAVI SINGH', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'PANKAJ SINGH', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'VIKRAM SINGH', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'SHIV KUMAR', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'RAJESH KUMAR', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'KULDEEP SINGH', regiment: 'GORKHA REGIMENT' },
{ rank: 'SEP', name: 'MANOJ KUMAR', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'HARIOM KUMAR', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'DEVINDER SINGH', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'RAJINDER SINGH', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'RAJESH SINGH', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'PANKAJ SINGH', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'VIRENDER KUMAR', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'AMIT KUMAR', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'RAJINDER KUMAR', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'MANOJ KUMAR', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'RAJESH KUMAR', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'ASHOK SINGH', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'VIKRAM KUMAR', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'RAJINDER SINGH', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'SURESH KUMAR', regiment: 'GORKHA REGIMENT' },
{ rank: 'SEP', name: 'RAJESH SINGH', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'JAGDISH KUMAR', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'MANOJ SINGH', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'RAKESH SINGH', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'VIRENDER KUMAR', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'SANTOSH SINGH', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'RAJESH KUMAR', regiment: 'GORKHA REGIMENT' },
{ rank: 'SEP', name: 'DEVENDER KUMAR', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'VIRENDER SINGH', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'AMIT SINGH', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'RAJINDER SINGH', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'RAVI KUMAR', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'RAJESH KUMAR', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'ASHOK KUMAR', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'VIKRAM KUMAR', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'MANOJ KUMAR', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'DEVENDER SINGH', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'HARIOM SINGH', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'RAJESH KUMAR', regiment: 'GORKHA REGIMENT' },
{ rank: 'SEP', name: 'PANKAJ SINGH', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'SANTOSH KUMAR', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'RAJINDER SINGH', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'VIRENDER SINGH', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'ASHOK SINGH', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'RAKESH SINGH', regiment: 'GORKHA REGIMENT' },
{ rank: 'SEP', name: 'PANKAJ KUMAR', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'SHAMSHER KUMAR', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'VIKRAM SINGH', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'RAJESH SINGH', regiment: 'RAJPUTANA RIFLES' },
{ rank: 'SEP', name: 'MANOJ SINGH', regiment: 'JAT REGIMENT' },
{ rank: 'SEP', name: 'RAJINDER KUMAR', regiment: 'RAJPUT REGIMENT' },
{ rank: 'SEP', name: 'VIKRAM KUMAR', regiment: 'SIKH REGIMENT' },
{ rank: 'SEP', name: 'VIRENDER KUMAR', regiment: 'GORKHA REGIMENT' },

  ];
  
  const SoldierList = () => {
    return (
      <div style={{  fontFamily: 'Arial, sans-serif' }}>
        <h2 style={{ textAlign: 'center', color: '#ffffff' }}>Kirti Chakra Awardees</h2><br />
        <table style={{ width: '100%', borderCollapse: 'collapse' }}>
          <thead>
            <tr>
              <th style={{ padding: '10px', border: '1px solid #b71c1c' }}>Rank</th>
              <th style={{ padding: '10px', border: '1px solid #b71c1c' }}>Name</th>
              <th style={{ padding: '10px', border: '1px solid #b71c1c' }}>Regiment</th>
            </tr>
          </thead>
          <tbody>
            {soldierData.map((soldier, index) => (
              <tr key={index}>
                <td style={{ padding: '10px', border: '1px solid #b71c1c' }}>{soldier.rank}</td>
                <td style={{ padding: '10px', border: '1px solid #b71c1c' }}>{soldier.name}</td>
                <td style={{ padding: '10px', border: '1px solid #b71c1c' }}>{soldier.regiment}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    );
  };
  
  export default SoldierList;
  