import React from 'react';

const officers = [
    
        { "sno": 1, "rank": "BRIG", "name": "RAJENDRA SINGH (P)", "regiment": "J&K STATE FORCES" },
        { "sno": 2, "rank": "BRIG", "name": "YADUNATH SINGH", "regiment": "INFANTRY" },
        { "sno": 3, "rank": "BRIG", "name": "M USMAN (P)", "regiment": "PARA" },
        { "sno": 4, "rank": "LT COL", "name": "IJS BUTALIA (P)", "regiment": "DOGRA" },
        { "sno": 5, "rank": "LT COL", "name": "MAN MOHAN KHANNA", "regiment": "KUMAON" },
        { "sno": 6, "rank": "LT COL", "name": "DEWAN RAJIT RAI (P)", "regiment": "SIKH" },
        { "sno": 7, "rank": "LT COL", "name": "RAJINDAR SINGH", "regiment": "ARMOURED" },
        { "sno": 8, "rank": "LT COL", "name": "HARBANS SINGH VIRK", "regiment": "PARA, MARATHA LI" },
        { "sno": 9, "rank": "LT COL", "name": "KAMAN SINGH", "regiment": "GARH RIF" },
        { "sno": 10, "rank": "LT COL", "name": "SHER JUNG THAPA", "regiment": "J&K INFANTRY" },
        { "sno": 11, "rank": "LT COL", "name": "THAKUR PRITHI CHAND", "regiment": "8 GORKHA RIF" },
        { "sno": 12, "rank": "MAJ", "name": "HARI CHAND", "regiment": "8 GORKHA RIF" },
        { "sno": 13, "rank": "MAJ", "name": "KHUSHAL CHAND", "regiment": "DOGRA" },
        { "sno": 14, "rank": "CAPT", "name": "ARVIND NILKHANTH JATAR", "regiment": "ARMOURED" },
        { "sno": 15, "rank": "SUB", "name": "BISHEN SINGH BAHADUR O.B.I (P)", "regiment": "SIKH" },
        { "sno": 16, "rank": "SUB", "name": "GURDIAL SINGH", "regiment": "PATIALA (RS)" },
        { "sno": 17, "rank": "JEM", "name": "HARDEV SINGH (P)", "regiment": "PATIALA (RS)" },
        { "sno": 18, "rank": "JEM", "name": "SAMPOORAN SINGH", "regiment": "PATIALA (RS)" },
        { "sno": 19, "rank": "JEM", "name": "NAND SINGH (P)", "regiment": "SIKH" },
        { "sno": 20, "rank": "HAV", "name": "CHUNI RAM", "regiment": "RAJ RIF" },
        { "sno": 21, "rank": "L/HAV", "name": "DAYA RAM", "regiment": "RAJPUT" },
        { "sno": 22, "rank": "NK", "name": "NAR SINGH (P)", "regiment": "KUMAON" },
        { "sno": 23, "rank": "NK", "name": "RAJU", "regiment": "MADRAS" },
        { "sno": 24, "rank": "NK", "name": "PRITAM SINGH", "regiment": "PATIALA (RS)" },
        { "sno": 25, "rank": "NK", "name": "KRISHNA SONAWANE", "regiment": "MAHAR" },
        { "sno": 26, "rank": "NK", "name": "SISHPAL SINGH (P)", "regiment": "JAT" },
        { "sno": 27, "rank": "NK", "name": "CHAND SINGH (P)", "regiment": "SIKH" },
        { "sno": 28, "rank": "L/NK", "name": "RABILAL THAPA (P)", "regiment": "1 GORKHA RIF" },
        { "sno": 29, "rank": "SEP", "name": "HARI SINGH", "regiment": "PATIALA (RS)" },
        { "sno": 30, "rank": "SEP", "name": "AMAR SINGH", "regiment": "PATIALA" },
        { "sno": 31, "rank": "SEP", "name": "DEWAN SINGH (P)", "regiment": "KUMAON" },
        { "sno": 32, "rank": "SEP", "name": "MAN SINGH (P)", "regiment": "KUMAON" },
        { "sno": 33, "rank": "C/DHOBY", "name": "RAM CHANDER", "regiment": "ENGINEERS" },
        { "sno": 34, "rank": "LT COL", "name": "ANANT SINGH PATHANIA", "regiment": "5 GORKHA RIF" },
        { "sno": 35, "rank": "MAJ", "name": "SATYA PAL CHOPRA (P)", "regiment": "MARATHA LI" },
        { "sno": 36, "rank": "MAJ", "name": "SARDAR MALKIT SINGH BRAR (P)", "regiment": "KUMAON" },
        { "sno": 37, "rank": "CAPT", "name": "DARA DINSHAW MISTRI (P)", "regiment": "ARTILLERY" },
        { "sno": 38, "rank": "LT", "name": "KISHAN SINGH RATHOR", "regiment": "RAJPUT" },
        { "sno": 39, "rank": "JEM", "name": "LAL SINGH", "regiment": "PATIALA" },
        { "sno": 40, "rank": "L/HAV", "name": "RAM PRASHAD GURUNG", "regiment": "5 GORKHA RIF" },
        { "sno": 41, "rank": "RFN", "name": "DHONKAL SINGH (P)", "regiment": "RAJ RIF" },
        { "sno": 42, "rank": "LT COL", "name": "AG RANGARAJA", "regiment": "AMC" },
        { "sno": 43, "rank": "BRIG", "name": "KANHYA LAL ATAL (P)", "regiment": "PARA BDE" },
        { "sno": 44, "rank": "LT COL", "name": "DHARAM SINGH", "regiment": "KUMAON" },
        { "sno": 45, "rank": "MAJ", "name": "ANIL KRISHNA BARAT", "regiment": "AMC" },
        { "sno": 46, "rank": "JEM", "name": "CHEWANG RINCHAN", "regiment": "J&K MILITIA" },
        { "sno": 47, "rank": "HAV", "name": "FATEH SINGH", "regiment": "JAT" },
        { "sno": 48, "rank": "HAV", "name": "LAL BAHADUR KHATTRI", "regiment": "9 GORKHA RIF" },
        { "sno": 49, "rank": "MAJ", "name": "NIRODE BARAN BANERJEA", "regiment": "AMC" },
        { "sno": 50, "rank": "MAJ", "name": "AK RAMASWAMY (P)", "regiment": "MARATHA LI" },
        { "sno": 51, "rank": "C/COOLIE", "name": "M ISMAIL", "regiment": "PATIALIA (RS)" },
        { "sno": 52, "rank": "NK", "name": "MAHABIR THAPA (P)", "regiment": "1 GORKHA RIF" },
        { "sno": 53, "rank": "L/NK", "name": "RAN BAHADUR GURUNG (P)", "regiment": "1 GORKHA RIF" },
        { "sno": 54, "rank": "SUB", "name": "SONAM STOPDHAN (P)", "regiment": "J&K MILITIA" },
  { "sno": 55, "rank": "HAV", "name": "SARUP SINGH (P)", "regiment": "J&K MILITIA" },
  { "sno": 56, "rank": "MAJ", "name": "SARDUL SINGH RANDHAWA", "regiment": "J&K MILITIA" },
  { "sno": 57, "rank": "MAJ", "name": "SHER PARTAP SINGH SHRIKENT", "regiment": "GARH RIF" },
  { "sno": 58, "rank": "MAJ", "name": "MAHANDER SINGH CHAUDHARY (P)", "regiment": "PUNJAB" },
  { "sno": 59, "rank": "MAJ", "name": "GURDIAL SINGH", "regiment": "RAJPUT" },
  { "sno": 60, "rank": "CAPT", "name": "MAHABIR PRASAD", "regiment": "SIKH" },
  { "sno": 61, "rank": "2/LT", "name": "GVP RAO (P)", "regiment": "GRENADIERS" },
  { "sno": 62, "rank": "NK", "name": "RABI LAL THAPA", "regiment": "8 GORKHA RIF" },
  { "sno": 63, "rank": "MAJ", "name": "AJIT SINGH", "regiment": "JAT" },
  { "sno": 64, "rank": "SEP", "name": "KEWAL SINGH (P)", "regiment": "SIKH" },
  { "sno": 65, "rank": "JEM", "name": "ISHE TUNDUP (P)", "regiment": "J&K MILITIA" },
  { "sno": 66, "rank": "HAV", "name": "STANGIN PHUNCHOK (P)", "regiment": "J&K MILITIA" },
  { "sno": 67, "rank": "2/LT", "name": "SHYAMAL DEV GOSWAMI", "regiment": "ARTILLERY" },
  { "sno": 68, "rank": "BRIG", "name": "TN RAINA", "regiment": "INFANTRY" },
  { "sno": 69, "rank": "NK", "name": "CHAIN SINGH (P)", "regiment": "PUNJAB" },
  { "sno": 70, "rank": "SEP", "name": "KANSHI RAK", "regiment": "PUNJAB" },
  { "sno": 71, "rank": "RFN", "name": "JASHWANT SINGH RAWAT (P)", "regiment": "GARH RIF" },
  { "sno": 72, "rank": "LT", "name": "VED PRAKASH TREHAN (P)", "regiment": "RAJ RIF" },
  { "sno": 73, "rank": "2/LT", "name": "BD DOGRA", "regiment": "GORKHA RIF" },
  { "sno": 74, "rank": "LT COL", "name": "BM BHATTACHARJEA", "regiment": "GARH RIF" },
  { "sno": 75, "rank": "MAJ", "name": "SK MATHUR", "regiment": "ARTILLERY" },
  { "sno": 76, "rank": "MAJ", "name": "BS RANDHAWA (P)", "regiment": "RAJPUT" },
  { "sno": 77, "rank": "LT COL", "name": "GURBANS SINGH SANGHA", "regiment": "MAHAR" },
  { "sno": 78, "rank": "MAJ", "name": "RANJIT SINGH DAYAL", "regiment": "PARA" },
  { "sno": 79, "rank": "MAJ", "name": "BHASKAR ROY", "regiment": "" },
  { "sno": 80, "rank": "CAPT", "name": "CHANDIR NARAIN SINGH (P)", "regiment": "GARH RIF" },
  { "sno": 81, "rank": "LT COL", "name": "SALIM CALEB", "regiment": "ARMOURED" },
  { "sno": 82, "rank": "LT COL", "name": "HL MEHTA (P)", "regiment": "MADRAS" },
  { "sno": 83, "rank": "LT COL", "name": "D HAYDE", "regiment": "JAT" },
  { "sno": 84, "rank": "SUB", "name": "AJIT SINGH (P)", "regiment": "SIKH" },
  { "sno": 85, "rank": "LT COL", "name": "NN KHANNA (P)", "regiment": "SIKH" },
  { "sno": 86, "rank": "MAJ", "name": "BHUPINDER SINGH (P)", "regiment": "ARMOURED" },
  { "sno": 87, "rank": "MAJ", "name": "R TYAGI (P)", "regiment": "JAT" },
  { "sno": 88, "rank": "MAJ GEN", "name": "RAJINDER SINGH, MVC", "regiment": "ARMOURED" },
  { "sno": 89, "rank": "MAJ GEN", "name": "GURSHAKSH SINGH", "regiment": "8 GORKHA RIF" },
  { "sno": 90, "rank": "MAJ GEN", "name": "HK SIHAB", "regiment": "GORKHA RIF" },
  { "sno": 91, "rank": "MAJ GEN", "name": "SS KALAAN, MC", "regiment": "RAJ RIF" },
  { "sno": 92, "rank": "BRIG", "name": "RD HIRA", "regiment": "11 GORKHA RIF" },
  { "sno": 93, "rank": "BRIG", "name": "KK SINGH", "regiment": "ARMOURED" },
  { "sno": 94, "rank": "BRIG", "name": "TK THEOGARAJA", "regiment": "ARMOURED" },
  { "sno": 95, "rank": "BRIG", "name": "ZC BAKSHI, VrC, VSM", "regiment": "5 GORKHA RIF" },
  { "sno": 96, "rank": "LT COL", "name": "MMS BAKSHI", "regiment": "ARMOURED" },
  { "sno": 97, "rank": "LT COL", "name": "RAGHUBIR SINGH", "regiment": "RAJ RIF" },
  { "sno": 98, "rank": "LT COL", "name": "AS VAIDYA", "regiment": "ARMOURED" },
  { "sno": 99, "rank": "LT COL", "name": "PK NANDAGOPAL", "regiment": "SIKH LI" },
  { "sno": 100, "rank": "CAPT", "name": "GAUTAM MUBAYI (P)", "regiment": "DOGRA" },
  { "sno": 101, "rank": "L/HAV", "name": "NAUBAT RAM", "regiment": "DOGRA" },
  { "sno": 102, "rank": "NK", "name": "DARSHAN SINGH (P)", "regiment": "SIKH LI" },
  { "sno": 103, "rank": "MAJ GEN", "name": "MOHINDAR SINGH,MC", "regiment": "ARTILLERY" },
  { "sno": 104, "rank": "LT COL", "name": "SAMPURAN SINGH", "regiment": "PUNJAB" },
  { "sno": 105, "rank": "CAPT", "name": "KAPIL SINGH THAPA (P)", "regiment": "JAT" },
  { "sno": 106, "rank": "SUB", "name": "TIKABAHADUR THAPA (P)", "regiment": "8 GORKHA RIF" },
  { "sno": 107, "rank": "LT COL", "name": "SANT SINGH", "regiment": "SIKH LI" },
  { "sno": 108, "rank": "LT COL", "name": "RAJ SINGH", "regiment": "GRENADIERS" },
  { "sno": 109, "rank": "MAJ", "name": "HAR BHAJAN SINGH (P)", "regiment": "RAJPUT" },
  { "sno": 110, "rank": "LT COL", "name": "MAHATAM SINGH", "regiment": "JAK RIF" },
  { "sno": 111, "rank": "2/LT", "name": "SHAMSHER SINGH (P)", "regiment": "GUARDS" },
  { "sno": 112, "rank": "SUB", "name": "MALKIAT SINGH (P)", "regiment": "PUNJAB" },
  { "sno": 113, "rank": "L/NK", "name": "RAM UGRAH PANDEY (P)", "regiment": "GUARDS" },
  { "sno": 114, "rank": "RFN", "name": "PATI RAM GURUNG (P)", "regiment": "1 GORKHA RIF" },
  { "sno": 115, "rank": "LT COL", "name": "HHS BHAWANI SINGH", "regiment": "PARA" },
  { "sno": 116, "rank": "MAJ", "name": "DALJIT SINGH NARAG (P)", "regiment": "ARMOURED" },
  { "sno": 117, "rank": "RFN", "name": "DIL BAHADUR CHETTRI", "regiment": "5 GORKHA RIF" },
  { "sno": 118, "rank": "BRIG", "name": "JOGINDER SINGH GHARAYA, KC, VSM", "regiment": "BIHAR" },
  { "sno": 119, "rank": "LT COL", "name": "PREM KUMAR KHANNA", "regiment": "SIKH" },
  { "sno": 120, "rank": "MAJ", "name": "ANUP SINGH GAHLAAT (P)", "regiment": "DOGRA" },
  { "sno": 121, "rank": "MAJ", "name": "BASDEV SINGH MANKOTIA", "regiment": "PUNJAB" },
  { "sno": 122, "rank": "SUB", "name": "MOHENDER SINGH", "regiment": "PUNJAB" },
  { "sno": 123, "rank": "SEP", "name": "PANDURANG SALUNKHE (P)", "regiment": "MARATHA LI" },
  { "sno": 124, "rank": "BRIG", "name": "ANANT VISHWANATH NATU", "regiment": "9 GORKHA RIF" },
  { "sno": 125, "rank": "LT COL", "name": "RAJ KUMAR SINGH", "regiment": "PUNJAB" },
  { "sno": 126, "rank": "MAJ", "name": "JAIVIR SINGH", "regiment": "SIKH" },
  { "sno": 127, "rank": "MAJ", "name": "KULDIP SINGH CHANDPURI", "regiment": "PUNJAB" },
  { "sno": 128, "rank": "MAJ", "name": "CHEWANG RINCHEN, MVC", "regiment": "LADAKH SCOUTS" },
  { "sno": 129, "rank": "BRIG", "name": "KRISHNA SWAMI GOWRI SHANKAR", "regiment": "SIGNALS" },
  { "sno": 130, "rank": "LT COL", "name": "KASHMIRI LAL RATTAN", "regiment": "SIKH" },
  { "sno": 131, "rank": "LT COL", "name": "RATTAN NATH SHARMA", "regiment": "PUNJAB" },
  { "sno": 132, "rank": "LT COL", "name": "SURRINDER KAPUR", "regiment": "JAK RIF" },
  { "sno": 133, "rank": "CAPT", "name": "PRADIP KUMAR GOUR (P)", "regiment": "ARTILLERY" },
  { "sno": 134, "rank": "LT COL", "name": "CHITOOR VENUGOPAL", "regiment": "1 GORKHA RIF" },
  { "sno": 135, "rank": "MAJ", "name": "VIJAY RATTAN CHOWDHARY (P)", "regiment": "ENGINEERS" },
  { "sno": 136, "rank": "L/NK", "name": "DRIG PAL SINGH (P)", "regiment": "RAJPUT" },
  { "sno": 137, "rank": "L/NK", "name": "AMAR BAHADUR CHHETRI", "regiment": "GUARDS" },
  { "sno": 138, "rank": "BRIG", "name": "MOHINDER LAL WHIG", "regiment": "5 GORKHA RIF" },
  { "sno": 139, "rank": "LT COL", "name": "HARISH CHANDRA PATHAK", "regiment": "SIKH LI" },
  { "sno": 140, "rank": "LT COL", "name": "KULWANT SINGH PANNU", "regiment": "PARA" },
  { "sno": 141, "rank": "MAJ", "name": "DHARAM VIR SINGH", "regiment": "GRENADIERS" },
  { "sno": 142, "rank": "COL", "name": "UDAI SINGH", "regiment": "8 GORKHA RIF" },
  { "sno": 143, "rank": "LT COL", "name": "SUKHJIT SINGH", "regiment": "SCINDE ARMOURED" },
  { "sno": 144, "rank": "A/COMDT", "name": "RAM KRISHNA WADHWA (P)", "regiment": "ARTILLERY BSF" },
  { "sno": 145, "rank": "BRIG", "name": "SANT SINGH, MVC", "regiment": "SIKH LI" },
  { "sno": 146, "rank": "BRIG", "name": "HARDEV SINGH KLER, AVSM", "regiment": "SIGNALS" },
  { "sno": 147, "rank": "BRIG", "name": "ANTHONY HEROLD EDWARD MICHIGAN", "regiment": "GRENADIERS" },
  { "sno": 148, "rank": "LT COL", "name": "VED PRAKASH GHAI (P)", "regiment": "MADRAS" },
  { "sno": 149, "rank": "CAPT", "name": "SHANKAR SHANKHAPAN WALKAR (P)", "regiment": "MADRAS" },
  { "sno": 150, "rank": "HAV", "name": "BIR BAHADUR PUN", "regiment": "1 GORKHA RIF" },
  { "sno": 151, "rank": "HAV", "name": "THOMAS PHILIPOSE", "regiment": "MADRAS" },
  { "sno": 152, "rank": "L/NK", "name": "SHANGARA SINGH (P)", "regiment": "SIKH" },
  { "sno": 153, "rank": "LT COL", "name": "VED PARAKASH AIRY", "regiment": "GRENADIERS" },
  { "sno": 154, "rank": "LT COL", "name": "RAJ MOHAN VOHRA", "regiment": "ARMOURED" },
  { "sno": 155, "rank": "LT COL", "name": "MANUT SINGH", "regiment": "ARMOURED" },
  { "sno": 156, "rank": "MAJ", "name": "AMARJIT SINGH BAL", "regiment": "ARMOURED" },
  { "sno": 157, "rank": "BRIG", "name": "JOGINDER SINGH BAKSHI", "regiment": "JAT" },
  { "sno": 158, "rank": "SEP", "name": "ANSUYA PRASAD (P)", "regiment": "MAHAR" },
  { "sno": 159, "rank": "BRIG", "name": "ARUN SHRIDHAR VAIDYA, MVC, AVSM", "regiment": "ARMOURED" },
  { "sno": 160, "rank": "CAPT", "name": "DEVINDER SINGH AHLAWAT (P)", "regiment": "DOGRA" },
  { "sno": 161, "rank": "LT COL", "name": "SHAMSHER SINGH", "regiment": "GUARDS" },
  { "sno": 162, "rank": "MAJ", "name": "VIJAY KUMAR BERRY", "regiment": "PARA" },
  { "sno": 163, "rank": "BRIG", "name": "ANAND SARUP", "regiment": "8 GORKHA RIF" },
  { "sno": 164, "rank": "NK", "name": "SUGAN SINGH (P)", "regiment": "RAJ RIF" },
  { "sno": 165, "rank": "BRIG", "name": "KAILAS PRASAD PANDE", "regiment": "ARTILLERY" },
  { "sno": 166, "rank": "LT COL", "name": "NARINDER SINGH SANDHU", "regiment": "DOGRA" },
  { "sno": 167, "rank": "LT COL", "name": "ARUN BHIMRAO HAROLIBA", "regiment": "5 GORKHA RIF" },
  { "sno": 168, "rank": "BRIG", "name": "MANJIT SINGH", "regiment": "INFANTRY" },
  { "sno": 169, "rank": "LT COL", "name": "INDER BAL SINGH SINGH BAWA", "regiment": "5 GORKHA RIF" },
  { "sno": 170, "rank": "MAJ", "name": "PS GANAPATHY", "regiment": "MAHAR" },
  { "sno": 171, "rank": "MAJ", "name": "KRISHNAGOPAL CHATTERJEE", "regiment": "4 GORKHA RIF" },
  { "sno": 172, "rank": "SUB", "name": "SANSAR CHAND", "regiment": "JAK LI" },
  { "sno": 173, "rank": "L/HAV", "name": "NAR BAHADUR ALE", "regiment": "4 GORKHA RIF" },
  { "sno": 174, "rank": "NK", "name": "PREM BAHADUR GURUNG", "regiment": "4 GORKHA RIF" },
  { "sno": 175, "rank": "CAPT", "name": "PRATAP SINGH (P)", "regiment": "AMC" },
  { "sno": 176, "rank": "COL", "name": "VIJAY KUMAR BAKSHI (P)", "regiment": "8 GORKHA RIF" },
  { "sno": 177, "rank": "2/LT", "name": "RAJEEV SANDHU (P)", "regiment": "ASSAM" },
  { "sno": 178, "rank": "MAJ", "name": "SONAM WANGCHUK", "regiment": "ASSAM" },
  { "sno": 179, "rank": "MAJ", "name": "VIVEK GUPTA (P)", "regiment": "RAJ RIF" },
  { "sno": 180, "rank": "MAJ", "name": "RAJESH SINGH ADHIKARI (P)", "regiment": "MECH INFANTRY, GRENADIERS" },
  { "sno": 181, "rank": "MAJ", "name": "PADMAPANI ACHARYA (P)", "regiment": "RAJ RIF" },
  { "sno": 182, "rank": "CAPT", "name": "ANUJ NAYYAR (P)", "regiment": "JAT" },
  { "sno": 183, "rank": "CAPT", "name": "NEIKEZHAKUO KENGURUSE (P)", "regiment": "ASC, RAJ RIF" },
  { "sno": 184, "rank": "LT", "name": "KEISHING CLIFFORD NONGRUM (P)", "regiment": "JAK LI" },
  { "sno": 185, "rank": "LT", "name": "BALWAN SINGH", "regiment": "GRENADIERS" },
  { "sno": 186, "rank": "NK", "name": "DIGENDRA KUMAR", "regiment": "RAJ RIF" },
  { "sno": 187, "rank": "SEP", "name": "IMLIAKUM AONAGA", "regiment": "" },
    { "sno": 188, "rank": "CAPT", "name": "GURJINDER SINGH SURI (P)", "regiment": "AOC" }
        

];

const OfficerList = () => {
  return (
    <div style={{ overflowX: 'auto' }}>
        <h2 style={{ textAlign: 'center', color: '#ffffff' }}>Mahavir Chakra Awardees</h2><br />
      <table style={{ width: '100%', borderCollapse: 'collapse' }}>
        <thead>
          <tr>
            <th style={{ border: '1px solid #b71c1c', padding: '8px' }}>S No</th>
            <th style={{ border: '1px solid #b71c1c', padding: '8px' }}>Rank</th>
            <th style={{ border: '1px solid #b71c1c', padding: '8px' }}>Name</th>
            <th style={{ border: '1px solid #b71c1c', padding: '8px' }}>Regiment</th>
          </tr>
        </thead>
        <tbody>
          {officers.map((officer) => (
            <tr key={officer.sno}>
              <td style={{ border: '1px solid #b71c1c', padding: '8px' }}>{officer.sno}</td>
              <td style={{ border: '1px solid #b71c1c', padding: '8px' }}>{officer.rank}</td>
              <td style={{ border: '1px solid #b71c1c', padding: '8px' }}>{officer.name}</td>
              <td style={{ border: '1px solid #b71c1c', padding: '8px' }}>{officer.regiment}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default OfficerList;
