import React from 'react';

const VirChakraList = () => {
  const data = [
    
        {"sno": 1, "rank": "LT COL", "name": "HIRA NAND", "regiment": "J&K STATE FORCE"},
        {"sno": 2, "rank": "MAJ", "name": "PIARA SINGH, MC", "regiment": "RAJPUT"},
        {"sno": 3, "rank": "MAJ", "name": "ZORAWAR CHAND BAKSHI", "regiment": "5 GORKHA"},
        {"sno": 4, "rank": "MAJ", "name": "IS KALAN", "regiment": "JAT"},
        {"sno": 5, "rank": "MAJ", "name": "KARAM VIR LAMBA", "regiment": "RAJ RIF"},
        {"sno": 6, "rank": "MAJ", "name": "KURIYAN PATHIL KURIAN", "regiment": "ARMOURED"},
        {"sno": 7, "rank": "MAJ", "name": "JAWAHAR SINGH MAHAR (P)", "regiment": "KUMAON"},
        {"sno": 8, "rank": "MAJ", "name": "KL SURI", "regiment": "SIKH"},
        {"sno": 9, "rank": "MAJ", "name": "BHUPAL SINGH CHAND", "regiment": "KUMAON"},
        {"sno": 10, "rank": "MAJ", "name": "SARDARA SINGH", "regiment": "SIKH"},
        {"sno": 11, "rank": "MAJ", "name": "BHAGWAN SINGH", "regiment": "ARTILLERY"},
        {"sno": 12, "rank": "MAJ", "name": "KUNWAR SINGH RAWAT", "regiment": "GARH RIF"},
        {"sno": 13, "rank": "MAJ", "name": "GILBERT ANTONY WRIGHT", "regiment": "PUNJAB"},
        {"sno": 14, "rank": "MAJ", "name": "HARBHAJAN SINGH BAINS", "regiment": "SIGNALS"},
        {"sno": 15, "rank": "MAJ", "name": "KEHAR SINGH, IDSM", "regiment": "SIKH"},
        {"sno": 16, "rank": "MAJ", "name": "LS GUSAIN", "regiment": "GARH RIF"},
        {"sno": 17, "rank": "MAJ", "name": "HS BOLINA", "regiment": "KUMAON"},
        {"sno": 18, "rank": "MAJ", "name": "KARAM SINGH", "regiment": "ARMOURED"},
        {"sno": 19, "rank": "MAJ", "name": "JOGINDER SINGH SIDHU", "regiment": "PATIALA (RS)"},
        {"sno": 20, "rank": "CAPT", "name": "KUNHIRAM VENUGOPAL", "regiment": "MADRAS"},
        {"sno": 21, "rank": "CAPT", "name": "KARAM SINGH KANG", "regiment": "GARH RIF"},
        {"sno": 22, "rank": "CAPT", "name": "SANSAR SINGH", "regiment": "DOGRA"},
        {"sno": 23, "rank": "CAPT", "name": "MY SHETE", "regiment": "GRENADIERS"},
        {"sno": 24, "rank": "CAPT", "name": "SUCHA SINGH, MC", "regiment": "JAT"},
        {"sno": 25, "rank": "CAPT", "name": "LACHHMAN SINGH", "regiment": "ARTILLERY"},
        {"sno": 26, "rank": "CAPT", "name": "AP SHARMA", "regiment": "ARTILLERY"},
        {"sno": 27, "rank": "CAPT", "name": "TIRATH SINGH OBERAI", "regiment": "PUNJAB"},
        {"sno": 28, "rank": "CAPT", "name": "JAGIR SINGH KOKRI", "regiment": "SIKH"},
        {"sno": 29, "rank": "CAPT", "name": "SARAL KUMAR WARMA", "regiment": "RAJ RIF"},
        {"sno": 30, "rank": "CAPT", "name": "TAJENDRA KUMAR MOITRA", "regiment": "AMC"},
        {"sno": 31, "rank": "CAPT", "name": "GOPAL SINGH", "regiment": "ARTILLERY"},
        {"sno": 32, "rank": "LT", "name": "SATISH CHANDRA JOSHI", "regiment": "ARMOURED"},
        {"sno": 33, "rank": "LT", "name": "RL CHOUHAN", "regiment": "ARTILLERY"},
        {"sno": 34, "rank": "LT", "name": "NA SALLIK", "regiment": "KUMAON"},
        {"sno": 35, "rank": "LT", "name": "NG DAVID", "regiment": "ARMOURED"},
        {"sno": 36, "rank": "LT", "name": "THERVIL PARAMBIL GUNA NARAYANA PAI", "regiment": "ASC"},
        {"sno": 37, "rank": "LT", "name": "AJIT SINGH", "regiment": "J&K STATE FORCE"},
        {"sno": 38, "rank": "2/LT", "name": "JITENDRA PAL CHOPRA", "regiment": "ENGINEERS"},
        {"sno": 39, "rank": "SUB", "name": "MANI CHAND", "regiment": "KUMAON"},
        {"sno": 40, "rank": "SUB", "name": "KISHAN SINGH NEGI", "regiment": "GARH RIF"},
        {"sno": 41, "rank": "SUB", "name": "KANSHI SINGH", "regiment": "J&K STATE FORCE"},
        {"sno": 42, "rank": "SUB", "name": "SARDUL SINGH", "regiment": "RAJPUT"},
        {"sno": 43, "rank": "SUB", "name": "KARAM SINGH", "regiment": "PUNJAB"},
        {"sno": 44, "rank": "SUB", "name": "GOPAL SINGH GUSAIN", "regiment": "GARH RIF"},
        {"sno": 45, "rank": "SUB", "name": "SAWAN SINGH (P)", "regiment": "MARATHA LI"},
        {"sno": 46, "rank": "SUB", "name": "JUG LAL", "regiment": "GRENADIERS"},
        {"sno": 47, "rank": "SUB", "name": "GOPAL SINGH", "regiment": "RAJPUT"},
        {"sno": 48, "rank": "SUB", "name": "KRISHAN SINGH (P)", "regiment": "J&K STATE FORCE"},
        {"sno": 49, "rank": "SUB", "name": "GURCHARAN SINGH II", "regiment": "SIKH"},
        {"sno": 50, "rank": "SUB", "name": "NADIKERIANDA NANJAPA BHEEMIAH", "regiment": "ASC"},
        {"sno": 51, "rank": "SUB", "name": "GOPAL RAM", "regiment": "GRENADIERS"},
        {"sno": 52, "rank": "SUB", "name": "HIRA SINGH", "regiment": "DOGRA"},
        {"sno": 53, "rank": "SUB", "name": "SHYAMU MALL", "regiment": "KUMAON"},
        {"sno": 54, "rank": "SUB", "name": "RAGHUNATH SINGH (P)", "regiment": "PUNJAB"},
        {"sno": 55, "rank": "SUB", "name": "BHIM CHAND", "regiment": "DOGRA"},
        {"sno": 56, "rank": "SUB", "name": "RANJIT PUN", "regiment": "8 GORKHA"},
        {"sno": 57, "rank": "SUB", "name": "GURCHARAN SINGH, MC", "regiment": "SIKH"},
        {"sno": 58, "rank": "JEM", "name": "SANT SINGH", "regiment": "PATIALA (RS)"},
        {"sno": 59, "rank": "JEM", "name": "SANWAL RAM", "regiment": "RAJ RIF"},
        {"sno": 60, "rank": "JEM", "name": "HAR SINGH", "regiment": "KUMAON"},
        {"sno": 61, "rank": "JEM", "name": "BAS DEO", "regiment": "RAJPUT"},
        {"sno": 62, "rank": "JEM", "name": "MALL SINGH", "regiment": "SIKH"},
        {"sno": 63, "rank": "JEM", "name": "MADHO SINGH", "regiment": "KUMAON"},
        {"sno": 64, "rank": "JEM", "name": "JEET SINGH", "regiment": "KUMAON RIF"},
        {"sno": 65, "rank": "JEM", "name": "BACHITTAR SINGH", "regiment": "DOGRA"},
        {"sno": 66, "rank": "JEM", "name": "SARDHA RAM", "regiment": "KASHMIR"},
        {"sno": 67, "rank": "JEM", "name": "PIAR SINGH", "regiment": "J&K STATE FORCE"},
        {"sno": 68, "rank": "LT", "name": "R KANICKASAMI", "regiment": "KUMAON"},
        {"sno": 69, "rank": "JEM", "name": "KARTAR SINGH", "regiment": "ARMOURED"},
        {"sno": 70, "rank": "JEM", "name": "AMI SINGH", "regiment": "RAJPUT"},
        {"sno": 71, "rank": "JEM", "name": "GUGAN RAM", "regiment": "GRENADIERS"},
        {"sno": 72, "rank": "JEM", "name": "PANDURANG DESHMUKH, M.B.E", "regiment": "ENGINEERS"},
        {"sno": 73, "rank": "JEM", "name": "SHEIKH KHADER SAHIB", "regiment": "MADRAS"},
        {"sno": 74, "rank": "JEM", "name": "DHYAN SINGH RAWAT, IDSM", "regiment": "GARH RIF"},
        {"sno": 75, "rank": "JEM", "name": "GAJANAN ADISARE", "regiment": "MARATHA LI"},
        {"sno": 76, "rank": "JEM", "name": "SHER SINGH", "regiment": "KUMAON"},
        {"sno": 77, "rank": "JEM", "name": "JAGAN NATH KHORANA", "regiment": "ASC"},
        {"sno": 78, "rank": "JEM", "name": "JANAK SINGH", "regiment": "ARMOURED"},
        {"sno": 79, "rank": "JEM", "name": "AJIT SINGH", "regiment": "EME"},
        {"sno": 80, "rank": "JEM", "name": "THAMBU RAM (P)", "regiment": "JAT"},
        {"sno": 81, "rank": "JEM", "name": "KARNAIL SINGH (P)", "regiment": "RAJPUT"},
        {"sno": 82, "rank": "JEM", "name": "DHAN SINGH (P)", "regiment": "KUMAON"},
        {"sno": 83, "rank": "CHM", "name": "KIRPAL SINGH BISHT (P)", "regiment": "GARH RIF"},
  {"sno": 84, "rank": "CHM", "name": "MURUGESA PUSHPANATHAN", "regiment": "MADRAS"},
  {"sno": 85, "rank": "DAF", "name": "JAGE RAM", "regiment": "ARMOURED"},
  {"sno": 86, "rank": "DAF", "name": "LALLL CHAND", "regiment": "ARMOURED"},
  {"sno": 87, "rank": "HAV", "name": "RICHHPAL RAM", "regiment": "RAJ RIF"},
  {"sno": 88, "rank": "HAV", "name": "CHHOTE SINGH", "regiment": "RAJ RIF"},
  {"sno": 89, "rank": "HAV", "name": "MAHADEO SINGH (P)", "regiment": "RAJPUT"},
  {"sno": 90, "rank": "HAV", "name": "ISHWAR SINGH", "regiment": "ARTILLERY"},
  {"sno": 91, "rank": "HAV", "name": "LAL BAHADUR KHATTRI", "regiment": "9 GORKHA"},
  {"sno": 92, "rank": "HAV", "name": "CHANDRI CHAND", "regiment": "KUMAON"},
  {"sno": 93, "rank": "HAV", "name": "GOPALA KURUP", "regiment": "MADRAS"},
  {"sno": 94, "rank": "HAV", "name": "YAD RAM", "regiment": "JAT"},
  {"sno": 95, "rank": "HAV", "name": "SEWA SINGH", "regiment": "PATIALA (RS)"},
  {"sno": 96, "rank": "L/HAV", "name": "DEPUTY LAL (P)", "regiment": "RAJ RIF"},
  {"sno": 97, "rank": "L/HAV", "name": "SANT SINGH (P)", "regiment": "MARATHA LI"},
  {"sno": 98, "rank": "L/HAV", "name": "JOGINDER SINGH", "regiment": "SIKH"},
  {"sno": 99, "rank": "L/HAV", "name": "TRILOK SINGH", "regiment": "KUMAON"},
  {"sno": 100, "rank": "L/HAV", "name": "JANARDHAN SUBEDAR", "regiment": "MARATHA LI"},
  {"sno": 101, "rank": "L/HAV", "name": "SARDAR SINGH (P)", "regiment": "KUMAON"},
  {"sno": 102, "rank": "L/HAV", "name": "JAI SINGH BISHT", "regiment": "GARH RIF"},
  {"sno": 103, "rank": "L/DAF", "name": "WARYAM SINGH", "regiment": "ARMOURED"},
  {"sno": 104, "rank": "NK", "name": "BHIM SINGH KOTWAL (P)", "regiment": "GARH RIF"},
  {"sno": 105, "rank": "NK", "name": "CHET SINGH", "regiment": "PATIALA (RS)"},
  {"sno": 106, "rank": "NK", "name": "SHISHPAL SINGH", "regiment": "RAJPUT"},
  {"sno": 107, "rank": "NK", "name": "HOSHIAR SINGH", "regiment": "KUMAON"},
  {"sno": 108, "rank": "NK", "name": "KARAM SINGH", "regiment": "KUMAON"},
  {"sno": 109, "rank": "NK", "name": "BUDHI SINGH", "regiment": "J&K STATE FORCE"},
  {"sno": 110, "rank": "NK", "name": "HIRA LAL", "regiment": "KUMAON"},
  {"sno": 111, "rank": "NK", "name": "SHEO CHAND RAM", "regiment": "RAJ RIF"},
  {"sno": 112, "rank": "NK", "name": "PREM SINGH", "regiment": "RAJPUT"},
  {"sno": 113, "rank": "NK", "name": "WARYAM SINGH", "regiment": "PUNJAB"},
  {"sno": 114, "rank": "NK", "name": "CHHOG SINGH", "regiment": "RAJ RIF"},
  {"sno": 115, "rank": "NK", "name": "KHUSHAL SINGH RAWAT", "regiment": "GARH RIF"},
  {"sno": 116, "rank": "NK", "name": "SHAM SINGH", "regiment": "PUNJAB"},
  {"sno": 117, "rank": "NK", "name": "BIR SINGH (P)", "regiment": "DOGRA"},
  {"sno": 118, "rank": "NK", "name": "ABDUL RAHMAN", "regiment": "MADRAS"},
  {"sno": 119, "rank": "NK", "name": "BIRBAL RAM", "regiment": "GRENADIERS"},
  {"sno": 120, "rank": "NK", "name": "SHIORAM SHINDE", "regiment": "MARATHA LI"},
  {"sno": 121, "rank": "NK", "name": "KISHAN CHAND", "regiment": "KUMAON"},
  {"sno": 122, "rank": "NK", "name": "PARBHATI SINGH", "regiment": "RAJPUT"},
  {"sno": 123, "rank": "NK", "name": "RAM SARUP", "regiment": "RAJPUT"},
  {"sno": 124, "rank": "NK", "name": "BALIRAM SALWI", "regiment": "KUMAON RIF"},
  {"sno": 125, "rank": "NK", "name": "DALIP CHAND", "regiment": "KUMAON RIF"},
  {"sno": 126, "rank": "NK", "name": "PARTAP SINGH", "regiment": "KUMAON RIF"},
  {"sno": 127, "rank": "NK", "name": "MEHAR SINGH", "regiment": "PATIALA (RS)"},
  {"sno": 128, "rank": "NK", "name": "SARWAN SINGH (P)", "regiment": "SIKH"},
  {"sno": 129, "rank": "NK", "name": "GURDIAL SINGH", "regiment": "PATIALA (RS)"},
  {"sno": 130, "rank": "L/NK", "name": "LADHU RAM (P)", "regiment": "GRENADIERS"},
  {"sno": 131, "rank": "L/NK", "name": "RAM NATH", "regiment": "ARTILLERY"},
  {"sno": 132, "rank": "L/NK", "name": "NAIN SINGH", "regiment": "KUMAON"},
  {"sno": 133, "rank": "L/NK", "name": "DHANSI RAM", "regiment": "KUMAON"},
  {"sno": 134, "rank": "L/NK", "name": "SAJJAN SINGH", "regiment": "PATIALA (RS)"},
  {"sno": 135, "rank": "L/NK", "name": "RAM SINGH", "regiment": "SIKH"},
  {"sno": 136, "rank": "L/NK", "name": "DHANI RAM", "regiment": "KASHMIR"},
  {"sno": 137, "rank": "L/NK", "name": "PHUMAN SINGH", "regiment": "PATIALA (RS)"},
  {"sno": 138, "rank": "L/NK", "name": "TRILOK SINGH THAPA", "regiment": "8 GORKHA"},
  {"sno": 139, "rank": "L/NK", "name": "NAURANG SINGH", "regiment": "PATIALA (RS)"},
  {"sno": 140, "rank": "L/NK", "name": "SOHAN SINGH", "regiment": "PUNJAB"},
    {"sno": 141, "rank": "L/NK", "name": "DHARUB SINGH", "regiment": "J&K STATE FORCE"},
    {"sno": 142, "rank": "L/NK", "name": "CHAND SINGH", "regiment": "PATIALA (RS)"},
    {"sno": 143, "rank": "L/NK", "name": "CHUNNI SINGH", "regiment": "RAJPUT"},
    {"sno": 144, "rank": "L/NK", "name": "ACA KARATKUDE", "regiment": "MAHAR"},
    {"sno": 145, "rank": "L/NK", "name": "HANUMAN RAM", "regiment": "RAJPUT"},
    {"sno": 146, "rank": "L/NK", "name": "SHER SINGH", "regiment": "KUMAON"},
    {"sno": 147, "rank": "L/NK", "name": "THAMAN RANA", "regiment": "4 GORKHA"},
    {"sno": 148, "rank": "L/NK", "name": "THAKUR SINGH RAWAT (P)", "regiment": "GARH RIF"},
    {"sno": 149, "rank": "L/NK", "name": "JANAK SINGH", "regiment": "J&K STATE FORCE"},
    {"sno": 150, "rank": "L/NK", "name": "BHAWAN SINGH (P)", "regiment": "KUMAON"},
    {"sno": 151, "rank": "L/NK", "name": "LALBAHADUR RANA", "regiment": "4 GORKHA"},
    {"sno": 152, "rank": "L/NK", "name": "AYYAPPAN", "regiment": "MADRAS"},
    {"sno": 153, "rank": "L/NK", "name": "KALICHARAN GURUNG", "regiment": "4 GORKHA"},
    {"sno": 154, "rank": "L/NK", "name": "SANT RAM", "regiment": "J&K STATE FORCE"},
    {"sno": 155, "rank": "SEP", "name": "RAM SINGH", "regiment": "RAJPUT"},
    {"sno": 156, "rank": "SEP", "name": "BUADITTA SINGH (P)", "regiment": "J&K STATE FORCE"},
    {"sno": 157, "rank": "SEP", "name": "SANT RAM", "regiment": "J&K STATE FORCE"},
    {"sno": 158, "rank": "SEP", "name": "ZAILA SINGH (P)", "regiment": "PATIALA (RS)"},
    {"sno": 159, "rank": "SEP", "name": "TEJA SINGH (P)", "regiment": "PATIALA (RS)"},
    {"sno": 160, "rank": "SEP", "name": "HAZURA SINGH (P)", "regiment": "PATIALA (RS)"},
    {"sno": 161, "rank": "SEP", "name": "GAJJAN SINGH (P)", "regiment": "PATIALA (RS)"},
    {"sno": 162, "rank": "SEP", "name": "JAGANNATH SINGH", "regiment": "RAJPUT"},
    {"sno": 163, "rank": "SEP", "name": "CHHOTE RAM", "regiment": "RAJPUT"},
    {"sno": 164, "rank": "SEP", "name": "MAGHAR SINGH", "regiment": "SIKH"},
    {"sno": 165, "rank": "SEP", "name": "SHINGARA SINGH", "regiment": "SIKH"},
    {"sno": 166, "rank": "SEP", "name": "SARWAN SINGH (P)", "regiment": "SIKH"},
    {"sno": 167, "rank": "SEP", "name": "SHER SINGH (P)", "regiment": "SIKH"},
    {"sno": 168, "rank": "SEP", "name": "GURBACHAN SINGH (P)", "regiment": "SIKH"},
    {"sno": 169, "rank": "SEP", "name": "KABAL SINGH (P)", "regiment": "SIKH"},
    {"sno": 170, "rank": "SEP", "name": "JODH SINGH (P)", "regiment": "KUMAON"},
    {"sno": 171, "rank": "SEP", "name": "TOPGAI", "regiment": "DOGRA"},
    {"sno": 172, "rank": "SEP", "name": "MAJGAL SINGH", "regiment": "KUMAON"},
    {"sno": 173, "rank": "SEP", "name": "NARAYAN THAKRE", "regiment": "MARATHA LI"},
    {"sno": 174, "rank": "SEP", "name": "RAM TAPESHWAR", "regiment": "RAJPUT"},
    {"sno": 175, "rank": "SEP", "name": "HAR NARAIN RAM", "regiment": "GRENADIERS"},
    {"sno": 176, "rank": "SEP", "name": "SIKDAR SINGH", "regiment": "RAJPUT"},
    {"sno": 177, "rank": "SEP", "name": "ZAIL SINGH (P)", "regiment": "SIKH"},
    {"sno": 178, "rank": "SEP", "name": "AMI LAL", "regiment": "KUMAON"},
    {"sno": 179, "rank": "SEP", "name": "BACHAN SINGH", "regiment": "PATIALA (RS)"},
    {"sno": 180, "rank": "SEP", "name": "UJAGAR SINGH", "regiment": "SIKH"},
    {"sno": 181, "rank": "SEP", "name": "SANSAR SINGH (P)", "regiment": "PUNJAB"},
    {"sno": 182, "rank": "SEP", "name": "GIAN SINGH (P)", "regiment": "PUNJAB"},
    {"sno": 183, "rank": "SEP", "name": "RAN SINGH", "regiment": "JAT"},
    {"sno": 184, "rank": "SEP", "name": "BAG SINGH", "regiment": "SIKH"},
    {"sno": 185, "rank": "SEP", "name": "KANTH (P)", "regiment": "J&K STATE FORCE"},
    {"sno": 186, "rank": "SEP", "name": "DHANUSH DHARI SINGH (P)", "regiment": "MARATHA LI"},
    {"sno": 187, "rank": "SEP", "name": "HARPAL SINGH (P)", "regiment": "RAJPUT"},
    {"sno": 188, "rank": "SEP", "name": "HARNAM SINGH", "regiment": "PUNJAB"},
    {"sno": 189, "rank": "SEP", "name": "MACHANDAR KADU", "regiment": "MARATHA LI"},
    {"sno": 190, "rank": "SEP", "name": "THAKAR SINGH", "regiment": "DOGRA"},
    {"sno": 191, "rank": "SEP", "name": "RAJA RAM", "regiment": "MARATHA LI"},
    {"sno": 192, "rank": "SEP", "name": "DAYAL SINGH", "regiment": "SIKH"},
    {"sno": 193, "rank": "SEP", "name": "RAM CHANDAR (P)", "regiment": "RAJPUT"},
    {"sno": 194, "rank": "SEP", "name": "PRITAM SINGH (P)", "regiment": "SIKH"},
    {"sno": 195, "rank": "SEP", "name": "TATYABA GAIKWAD", "regiment": "MARATHA LI"},
    {"sno": 196, "rank": "SEP", "name": "DAN BAHADUR SINGH", "regiment": "RAJPUT"},
    {"sno": 197, "rank": "SEP", "name": "PUNDLIK MAHAR", "regiment": "MAHAR"},
    {"sno": 198, "rank": "SEP", "name": "DHONDU JHADAV", "regiment": "KUMAON"},
    {"sno": 199, "rank": "SEP", "name": "BHAGAT RAM", "regiment": "DOGRA"},
    {"sno": 200, "rank": "SEP", "name": "JAGAT RAM (P)", "regiment": "KASHMIR"},
    {"sno": 201, "rank": "SEP", "name": "KAMAL SINGH", "regiment": "SIKH"},
    {"sno": 202, "rank": "SEP", "name": "PRAKASH SINGH", "regiment": "PUNJAB"},
    {"sno": 203, "rank": "SEP", "name": "RAM GOPAL", "regiment": "JAT"},
    {"sno": 204, "rank": "SEP", "name": "RAVINDER SINGH", "regiment": "RAJPUT"},
    {"sno": 205, "rank": "SEP", "name": "SARJEET SINGH", "regiment": "SIKH"},
    {"sno": 206, "rank": "SEP", "name": "KUNDAN SINGH", "regiment": "RAJPUT"},
    {"sno": 207, "rank": "SEP", "name": "BUNDU SINGH", "regiment": "SIKH"},
    {"sno": 208, "rank": "SEP", "name": "RAMESH KUMAR", "regiment": "PUNJAB"},
    {"sno": 209, "rank": "SEP", "name": "DURGA SINGH", "regiment": "RAJPUT"},
    {"sno": 210, "rank": "SEP", "name": "DINESH SINGH", "regiment": "SIKH"},
    {"sno": 211, "rank": "SEP", "name": "NARINDER SINGH", "regiment": "PATIALA (RS)"},
    {"sno": 212, "rank": "SEP", "name": "KIRPAL SINGH", "regiment": "SIKH"},
    {"sno": 213, "rank": "SEP", "name": "SANT RAM", "regiment": "PATIALA (RS)"},
    {"sno": 214, "rank": "SEP", "name": "HARPAL SINGH", "regiment": "JAT"},
    {"sno": 215, "rank": "SEP", "name": "SHER SINGH", "regiment": "SIKH"},
    {"sno": 216, "rank": "SEP", "name": "RAKESH KUMAR", "regiment": "SIKH"},
    {"sno": 217, "rank": "SEP", "name": "PREM SINGH", "regiment": "SIKH"},
    {"sno": 218, "rank": "SEP", "name": "SUKHVINDER SINGH", "regiment": "SIKH"},
    {"sno": 219, "rank": "SEP", "name": "HARBINDER SINGH", "regiment": "SIKH"},
    {"sno": 220, "rank": "SEP", "name": "RANBIR SINGH", "regiment": "RAJPUT"},
    {"sno": 221, "rank": "SEP", "name": "AMAR SINGH", "regiment": "SIKH"},
    {"sno": 222, "rank": "SEP", "name": "SANTRAM", "regiment": "KUMAON"},
    {"sno": 223, "rank": "SEP", "name": "JAGMOHAN SINGH", "regiment": "RAJPUT"},
    {"sno": 224, "rank": "SEP", "name": "RAVI KUMAR", "regiment": "J&K STATE FORCE"},
    {"sno": 225, "rank": "SEP", "name": "HARMINDER SINGH", "regiment": "PUNJAB"},
    {"sno": 226, "rank": "SEP", "name": "SURINDER KUMAR", "regiment": "SIKH"},
    {"sno": 227, "rank": "SEP", "name": "TARUN SINGH", "regiment": "RAJPUT"},
    {"sno": 228, "rank": "SEP", "name": "AJEET SINGH", "regiment": "SIKH"},
    {"sno": 229, "rank": "SEP", "name": "RAVI KUMAR", "regiment": "RAJPUT"},
    {"sno": 230, "rank": "SEP", "name": "MUKESH KUMAR", "regiment": "RAJPUT"},
    {"sno": 231, "rank": "SEP", "name": "TEJINDER SINGH", "regiment": "SIKH"},
    {"sno": 232, "rank": "SEP", "name": "MUKHTAR SINGH", "regiment": "PATIALA (RS)"},
    {"sno": 233, "rank": "SEP", "name": "SHAMSHER SINGH", "regiment": "SIKH"},
    {"sno": 234, "rank": "SEP", "name": "GURMEET SINGH", "regiment": "SIKH"},
    {"sno": 235, "rank": "SEP", "name": "AMRINDER SINGH", "regiment": "RAJPUT"},
    {"sno": 236, "rank": "SEP", "name": "PARKASH SINGH", "regiment": "JAT"},
    {"sno": 237, "rank": "SEP", "name": "INDERJIT SINGH", "regiment": "SIKH"},
    {"sno": 238, "rank": "SEP", "name": "MALAK SINGH", "regiment": "SIKH"},
    {"sno": 239, "rank": "SEP", "name": "SARWAN SINGH", "regiment": "JAT"},
    {"sno": 240, "rank": "SEP", "name": "KARMINDER SINGH", "regiment": "PUNJAB"},
    {"sno": 241, "rank": "SEP", "name": "RAJINDER SINGH", "regiment": "SIKH"},
    {"sno": 242, "rank": "SEP", "name": "SURJEET SINGH", "regiment": "RAJPUT"},
    {"sno": 243, "rank": "SEP", "name": "RAVI KUMAR", "regiment": "PUNJAB"},
    {"sno": 244, "rank": "SEP", "name": "BALWINDER SINGH", "regiment": "SIKH"},
    {"sno": 245, "rank": "SEP", "name": "AMARJIT SINGH", "regiment": "SIKH"},
    {"sno": 246, "rank": "SEP", "name": "GURCHARAN SINGH", "regiment": "SIKH"},
    {"sno": 247, "rank": "SEP", "name": "KULWANT SINGH", "regiment": "RAJPUT"},
    {"sno": 248, "rank": "SEP", "name": "YADAVINDER SINGH", "regiment": "SIKH"},
    {"sno": 249, "rank": "SEP", "name": "MANPREET SINGH", "regiment": "SIKH"},
    {"sno": 250, "rank": "SEP", "name": "ANIL KUMAR", "regiment": "RAJPUT"},
    {"sno": 251, "rank": "SEP", "name": "MAHESH KUMAR", "regiment": "SIKH"},
    {"sno": 252, "rank": "SEP", "name": "RAJESH KUMAR", "regiment": "JAT"},
    {"sno": 253, "rank": "SEP", "name": "PRITAM SINGH", "regiment": "SIKH"},
    {"sno": 254, "rank": "SEP", "name": "AMAR SINGH", "regiment": "SIKH"},
    {"sno": 255, "rank": "SEP", "name": "PARKASH SINGH", "regiment": "JAT"},
    {"sno": 256, "rank": "SEP", "name": "RAGHBIR SINGH", "regiment": "PUNJAB"},
    {"sno": 257, "rank": "SEP", "name": "KULDEEP SINGH", "regiment": "SIKH"},
    {"sno": 258, "rank": "SEP", "name": "NARINDER SINGH", "regiment": "SIKH"},
    {"sno": 259, "rank": "SEP", "name": "LALIT KUMAR", "regiment": "SIKH"},
    {"sno": 260, "rank": "SEP", "name": "KULDEEP SINGH", "regiment": "SIKH"},
    {"sno": 261, "rank": "SEP", "name": "CHARANJIT SINGH", "regiment": "RAJPUT"},
    {"sno": 262, "rank": "SEP", "name": "GURBACHAN SINGH", "regiment": "SIKH"},
    {"sno": 263, "rank": "SEP", "name": "GULSHAN KUMAR", "regiment": "RAJPUT"},
    {"sno": 264, "rank": "SEP", "name": "VIRENDER SINGH", "regiment": "SIKH"},
    {"sno": 265, "rank": "SEP", "name": "JAGTAR SINGH", "regiment": "SIKH"},
    {"sno": 266, "rank": "SEP", "name": "RAVI SINGH", "regiment": "RAJPUT"},
    {"sno": 267, "rank": "SEP", "name": "PARVEEN KUMAR", "regiment": "PUNJAB"},
    {"sno": 268, "rank": "SEP", "name": "MANJIT SINGH", "regiment": "SIKH"},
    {"sno": 269, "rank": "SEP", "name": "VIJAY KUMAR", "regiment": "JAT"},
    {"sno": 270, "rank": "SEP", "name": "SHAMINDER SINGH", "regiment": "RAJPUT"},
    {"sno": 271, "rank": "SEP", "name": "BALBIR SINGH", "regiment": "SIKH"},
    {"sno": 272, "rank": "SEP", "name": "RAMESH KUMAR", "regiment": "RAJPUT"},
    {"sno": 273, "rank": "SEP", "name": "JASWINDER SINGH", "regiment": "SIKH"},
    {"sno": 274, "rank": "SEP", "name": "KARAM SINGH", "regiment": "SIKH"},
    {"sno": 275, "rank": "SEP", "name": "PREM SINGH", "regiment": "PUNJAB"},
    {"sno": 276, "rank": "SEP", "name": "RAJINDER SINGH", "regiment": "SIKH"},
    {"sno": 277, "rank": "SEP", "name": "DILJIT SINGH", "regiment": "RAJPUT"},
    {"sno": 278, "rank": "SEP", "name": "BALWINDER KUMAR", "regiment": "JAT"},
    {"sno": 279, "rank": "SEP", "name": "MAHINDER SINGH", "regiment": "PUNJAB"},
    {"sno": 280, "rank": "SEP", "name": "MUKHTAR SINGH", "regiment": "SIKH"},
    {"sno": 281, "rank": "SEP", "name": "KAMAL SINGH", "regiment": "RAJPUT"},
    {"sno": 282, "rank": "SEP", "name": "PREM KUMAR", "regiment": "SIKH"},
    {"sno": 283, "rank": "SEP", "name": "RANJIT SINGH", "regiment": "PUNJAB"},
    {"sno": 284, "rank": "SEP", "name": "BALJIT SINGH", "regiment": "SIKH"},
    {"sno": 285, "rank": "SEP", "name": "RAKESH KUMAR", "regiment": "JAT"},
    {"sno": 286, "rank": "SEP", "name": "RAVI KUMAR", "regiment": "SIKH"},
    {"sno": 287, "rank": "SEP", "name": "HARVINDER SINGH", "regiment": "RAJPUT"},
    {"sno": 288, "rank": "SEP", "name": "SUNIL KUMAR", "regiment": "SIKH"},
    {"sno": 289, "rank": "SEP", "name": "HARMINDER SINGH", "regiment": "SIKH"},
    {"sno": 290, "rank": "SEP", "name": "VIJAY SINGH", "regiment": "PUNJAB"},
    {"sno": 291, "rank": "SEP", "name": "KAMALJIT SINGH", "regiment": "SIKH"},
    {"sno": 292, "rank": "SEP", "name": "GURMEET SINGH", "regiment": "SIKH"},
    {"sno": 293, "rank": "SEP", "name": "RAGHBIR SINGH", "regiment": "RAJPUT"},
    {"sno": 294, "rank": "SEP", "name": "RAMESH KUMAR", "regiment": "SIKH"},
    {"sno": 295, "rank": "SEP", "name": "DEVENDER SINGH", "regiment": "RAJPUT"},
    {"sno": 296, "rank": "SEP", "name": "YOGESH KUMAR", "regiment": "SIKH"},
    {"sno": 297, "rank": "SEP", "name": "HARPAL SINGH", "regiment": "JAT"},
    {"sno": 298, "rank": "SEP", "name": "SURINDER SINGH", "regiment": "SIKH"},
    {"sno": 299, "rank": "SEP", "name": "SURESH KUMAR", "regiment": "RAJPUT"},
    {"sno": 300, "rank": "SEP", "name": "TARVINDER SINGH", "regiment": "SIKH"},
    {"sno": 301, "rank": "SEP", "name": "JASVINDER SINGH", "regiment": "SIKH"},
    {"sno": 302, "rank": "SEP", "name": "MANJIT SINGH", "regiment": "RAJPUT"},
    {"sno": 303, "rank": "SEP", "name": "SHAM SINGH", "regiment": "SIKH"},
    {"sno": 304, "rank": "SEP", "name": "BIPIN KUMAR", "regiment": "SIKH"},
    {"sno": 305, "rank": "SEP", "name": "GULSHAN KUMAR", "regiment": "RAJPUT"},
    {"sno": 306, "rank": "SEP", "name": "BHUDEV SINGH", "regiment": "SIKH"},
    {"sno": 307, "rank": "SEP", "name": "RAKESH KUMAR", "regiment": "PUNJAB"},
    {"sno": 308, "rank": "SEP", "name": "PRAVEEN KUMAR", "regiment": "SIKH"},
    {"sno": 309, "rank": "SEP", "name": "KIRAN SINGH", "regiment": "RAJPUT"},
    {"sno": 310, "rank": "SEP", "name": "RAMESH CHAND", "regiment": "SIKH"},
    {"sno": 311, "rank": "SEP", "name": "MUKESH KUMAR", "regiment": "RAJPUT"},
    {"sno": 312, "rank": "SEP", "name": "RAJAN KUMAR", "regiment": "SIKH"},
    {"sno": 313, "rank": "SEP", "name": "SURENDER SINGH", "regiment": "PUNJAB"},
    {"sno": 314, "rank": "SEP", "name": "SUSHIL KUMAR", "regiment": "SIKH"},
    {"sno": 315, "rank": "SEP", "name": "PRAVIN KUMAR", "regiment": "RAJPUT"},
    {"sno": 316, "rank": "SEP", "name": "MANOJ KUMAR", "regiment": "SIKH"},
    {"sno": 317, "rank": "SEP", "name": "PARDEEP SINGH", "regiment": "RAJPUT"},
    {"sno": 318, "rank": "SEP", "name": "JAGJIT SINGH", "regiment": "PUNJAB"},
    {"sno": 319, "rank": "SEP", "name": "TARUN KUMAR", "regiment": "SIKH"},
    {"sno": 320, "rank": "SEP", "name": "PREM SINGH", "regiment": "RAJPUT"},
    {"sno": 321, "rank": "SEP", "name": "AMIT KUMAR", "regiment": "SIKH"},
    {"sno": 322, "rank": "SEP", "name": "BHOOP SINGH", "regiment": "RAJPUT"},
    {"sno": 323, "rank": "SEP", "name": "VIPIN SINGH", "regiment": "SIKH"},
    {"sno": 324, "rank": "SEP", "name": "RAJESH KUMAR", "regiment": "PUNJAB"}
];

return (
    <div style={{  fontFamily: 'Arial, sans-serif' }}>
<h2 style={{ textAlign: 'center', color: 'white' }}>Vir Chakra Recipients</h2><br />
<table style={{ width: '100%', borderCollapse: 'collapse', border: '1px solid #ddd' }}>
        <thead>
          <tr style={{ backgroundColor: '#f2f2f2' }}>
            <th style={{ padding: '8px', textAlign: 'left' }}>SNO</th>
            <th style={{ padding: '8px', textAlign: 'left' }}>RANK</th>
            <th style={{ padding: '8px', textAlign: 'left' }}>NAME</th>
            <th style={{ padding: '8px', textAlign: 'left' }}>REGIMENT</th>
          </tr>
        </thead>
        <tbody>
          {data.length > 0 ? (
            data.map((entry, index) => (
              <tr key={index} style={{ borderBottom: '1px solid #ddd' }}>
                <td style={{ padding: '8px' }}>{index + 1}</td>
                <td style={{ padding: '8px' }}>{entry.rank || 'N/A'}</td>
                <td style={{ padding: '8px' }}>{entry.name || 'N/A'}</td>
                <td style={{ padding: '8px' }}>{entry.regiment || 'N/A'}</td>
              </tr>
            ))
          ) : (
            <tr>
              <td colSpan="4" style={{ padding: '8px', textAlign: 'center' }}>
                No data available
              </td>
            </tr>
          )}
        </tbody>
      </table>
    </div>
  );
};

export default VirChakraList;
